econia-labs/emojicoin-dot-fun

- doc/architecture-specification.md
Add assorted architecture specifications per recent engineering discussions
Passes `pre-commit`
> [ECO-1540] Update architecture specification

- src/move/emojicoin_dot_fun/sources/emojicoin_dot_fun.move
Add LP provider provider/remove simulation/commitment functions
```
git ls-files | entr -c aptos move compile --dev --package-dir src/move/emojicoin_dot_fun
```
Above throws warning but not error, planning to refactor with followup PR on some changes to #10 to prevent PR bloat, since this is relative to that
> [ECO-1568] Add LP provider functionality

- src/move/emojicoin_dot_fun/sources/emojicoin_dot_fun.move
I abstracted out the function logic to make sure that the logic for creating and registering a market is consistent and testable, and then I made sure it compiled and pases the move unit tests
Part of the reason I try to keep this logic out is because we can't run the `publish_bytecode` stuff in unit tests, so we can't actually call `register_market(...)` from a unit test. It's much easier to make sure it's accurate if the logic is encapsulated into separate functions that are isolated from the publishing logic.
```shell
aptos move test --dev
```
> [ECO-1586] Refactor market registration by moving function logic out so it's more testable and consistent

- src/move/emojicoin_dot_fun/sources/emojicoin_dot_fun.move
Refactor the market registration to consolidate borrows, func calls, etc., and add fee
charging.
Includes testing-friendly refactors per #17 , which merged into here as suggestions
See #17
> [ECO-1569] Refactor market registration

- src/move/emojicoin_dot_fun/sources/emojicoin_dot_fun.move
Tidy up assorted algorithms, tests
```sh
git ls-files | entr -c aptos move test --package-dir src/move/emojicoin_dot_fun --dev
```
> [ECO-1589] Tidy up algorithms

- src/move/emojicoin_dot_fun/sources/emojicoin_dot_fun.move
1. Add view functions for registry and market state
1. Add decoders for unpacking view returns
1. Add funcs for instantaneous analytics as needed
1. Grant non-key-able structs the maximum ability set
```sh
```
> [ECO-1570] Add view functions, decoders

- src/move/emojicoin_dot_fun/sources/emojicoin_dot_fun.move
Add market registration event definition and emission
```sh
git ls-files | entr -c aptos move test --dev --package-dir src/move/emojicoin_dot_fun
```
> [ECO-1622] Add market registration event

- src/typescript/frontend/package.json
- src/typescript/frontend/public/locales/en-US.json
- src/typescript/frontend/src/components/header/constants.ts
- src/typescript/frontend/src/components/header/index.tsx
- src/typescript/frontend/src/components/inputs/input/index.tsx
- src/typescript/frontend/src/components/svg/icons/Close.tsx
- src/typescript/frontend/src/hooks/use-tooltip/index.tsx
- src/typescript/frontend/src/pages/launch-emojicoin/hooks/types.ts
- src/typescript/frontend/src/pages/launch-emojicoin/hooks/use-validation-schema.ts
- src/typescript/frontend/src/pages/launch-emojicoin/index.tsx
- src/typescript/frontend/src/pages/launch-emojicoin/styled.tsx
- src/typescript/frontend/src/theme/base.ts
Added the ability to select multiple emojis
Added validation for a 10-byte limit
Added lazy loading for the emoji palette
Delete this line and provide a description of how to test the changes in this
PR.
you are not a member of Econia Labs)
> If a task does not apply to your PR, strike it through and mark it complete:
```md
```
> ECO-1628 Fix the Launch Emojicoin page

- src/move/emojicoin_dot_fun/README.md
Add to the package README instructions on publishing onchain using a multisig.
Published onchain using a multisig.
> [ECO-1645] Add multisig publication instructions

- src/typescript/frontend/public/locales/en-US.json
- src/typescript/frontend/src/components/pages/pools/components/liquidity/index.tsx
- src/typescript/frontend/src/components/pages/pools/components/pools-table/components/table-header/index.tsx
- src/typescript/frontend/src/components/pages/pools/components/pools-table/components/table-row-desktop/index.tsx
- src/typescript/frontend/src/components/pages/pools/components/pools-table/constants/index.ts
- src/typescript/frontend/src/components/pages/pools/components/pools-table/index.tsx
- src/typescript/frontend/src/components/pages/pools/components/table-header-switcher/index.tsx
- src/typescript/frontend/src/components/pages/pools/index.tsx
- src/typescript/frontend/src/components/pages/pools/styled.tsx
- src/typescript/frontend/src/lib/registry.tsx
Responsive Pools Page
Fixed console errors about custom element props
Delete this line and provide a description of how to test the changes in this
PR.
> If a task does not apply to your PR, strike it through and mark it complete:
```md
```
> [ECO 1675] Responsive Pools Page

- .github/actions/ts-run-tests/action.yaml
- .github/workflows/ts-run-tests.yaml
- .gitmodules
- cfg/cspell-dictionary.txt
- src/typescript/api/.env.example
- src/typescript/api/package.json
- src/typescript/api/pnpm-lock.yaml
- src/typescript/api/src/emojicoin_dot_fun/consts.ts
- src/typescript/api/tests/e2e/chat.test.ts
- src/typescript/api/tests/post-test.js
- src/typescript/api/tests/pre-test.js
- src/typescript/api/tests/utils/inbox.ts
- src/typescript/api/tests/utils/index.ts
- src/typescript/api/tests/utils/local-node.ts
This PR adds Inbox to the e2e tests.
Run `git submodule update --init --recursive`.
Run e2e tests.
> [ECO-1648] add inbox to e2e testing

- src/typescript/frontend/public/locales/en-US.json
- src/typescript/frontend/src/app/layout.tsx
- src/typescript/frontend/src/components/header/components/mobile-menu-item/index.tsx
- src/typescript/frontend/src/components/header/components/mobile-menu-item/styled.tsx
- src/typescript/frontend/src/components/header/components/mobile-menu-item/types.ts
- src/typescript/frontend/src/components/header/components/mobile-menu/index.tsx
- src/typescript/frontend/src/components/header/index.tsx
- src/typescript/frontend/src/components/modal/components/close-modal-wrapper/index.tsx
- src/typescript/frontend/src/components/modal/components/modal-wrapper/styled.tsx
- src/typescript/frontend/src/components/modal/components/styled.tsx
- src/typescript/frontend/src/components/modal/components/wallet-modal/index.tsx
- src/typescript/frontend/src/components/modal/components/wallet-modal/types.ts
- src/typescript/frontend/src/components/modal/constants.tsx
- src/typescript/frontend/src/components/pages/emojicoin/components/mobile-grid/styled.tsx
- src/typescript/frontend/src/components/pages/emojicoin/components/trade-history/components/table-row-desktop/index.tsx
- src/typescript/frontend/src/components/pages/emojicoin/components/trade-history/index.tsx
- src/typescript/frontend/src/components/pages/emojicoin/components/trade-history/styled.tsx
- src/typescript/frontend/src/components/pages/home/components/emoji-table/index.tsx
- src/typescript/frontend/src/components/pages/home/components/emoji-table/styled.tsx
- src/typescript/frontend/src/components/pages/home/components/table-card/styled.tsx
- src/typescript/frontend/src/components/pages/pools/components/pools-table/index.tsx
- src/typescript/frontend/src/components/svg/components/close-icon-with-hover/index.tsx
- src/typescript/frontend/src/components/svg/components/close-icon-with-hover/styled.tsx
- src/typescript/frontend/src/components/table/index.tsx
- src/typescript/frontend/src/context/providers.tsx
- src/typescript/frontend/src/context/styled.tsx
- src/typescript/frontend/src/store/modal/types.ts
- src/typescript/frontend/src/styles/GlobalStyle.tsx
Added modal window on click on wallet
Refactored scrollbar
Added horizontal scroll to the trade history table on the Emojicoin page on mobile width
Removed vertical scroll on all pages
Redesigned the table on the home page
Delete this line and provide a description of how to test the changes in this
PR.
> If a task does not apply to your PR, strike it through and mark it complete:
```md
```
> [ECO-1683] Fixes after responsive review

- src/typescript/api/src/emojicoin_dot_fun/emojicoin-dot-fun.ts
- src/typescript/api/src/types/contract.ts
- src/typescript/api/src/types/core.ts
- src/typescript/api/tests/e2e/register.test.ts
> [ECO-1693] Add `RegistryViewData` type and update the `AggregatorSnapshot` type

- .github/PULL_REQUEST_TEMPLATE.md
Update PR description template for semantic correctness/submission efficiency.
None
> [ECO-1682] Update PR template

- .github/workflows/ts-run-tests.yaml
- .gitmodules
- README.md
- cfg/cspell-dictionary.txt
> [ECO-1697] Add the `charting_library` git submodule

- .github/PULL_REQUEST_TEMPLATE.md
This PR cleans the PR template.
> [ECO-1682] simplify pr template

- README.md
Fix pre-commit badge to be at the top of repo README.
Local markdown view
> [ECO-1726] Update pre-commit badge

- src/typescript/frontend/src/app/emojicoin/[market]/page.tsx
- src/typescript/frontend/src/components/pages/emojicoin/components/chat/components/message-container/index.tsx
- src/typescript/frontend/src/components/pages/emojicoin/components/chat/components/message-container/styled.tsx
- src/typescript/frontend/src/components/pages/emojicoin/components/chat/components/message-container/types.ts
- src/typescript/frontend/src/components/pages/emojicoin/components/chat/index.tsx
- src/typescript/frontend/src/components/pages/emojicoin/components/desktop-grid/index.tsx
- src/typescript/frontend/src/components/pages/emojicoin/components/mobile-grid/index.tsx
- src/typescript/frontend/src/components/svg/components/close-icon-with-hover/index.tsx
- src/typescript/frontend/src/components/svg/icons/SendIcon.tsx
- src/typescript/sdk/src/types/types.ts
> [ECO 1751] Add chat functionality

- src/typescript/frontend/src/app/emojicoin/[market]/page.tsx
- src/typescript/frontend/src/app/home/page.tsx
- src/typescript/frontend/src/app/pools/page.tsx
- src/typescript/frontend/src/lib/utils/allowlist.ts
> [ECO-1787] Fix `server-env` imports

- src/typescript/frontend/package.json
- src/typescript/frontend/src/lib/env.ts
- src/typescript/frontend/src/lib/mqtt.ts
- src/typescript/pnpm-lock.yaml
This PR adds utility functions to connect to MQTT.
> [ECO-1747] add utility functions for mqtt

- src/typescript/frontend/src/configs/meta.ts
Fix metadata info from social preview, follow up to #114
Deployment builds
Social preview verified in chat application
> [ECO-1890] Make metadata tweaks

- src/typescript/frontend/src/app/pools/api/route.ts
- src/typescript/frontend/src/components/pages/home/components/emoji-table/components/FilterOptions.tsx
- src/typescript/frontend/src/components/pages/home/components/emoji-table/components/buttons-block/index.tsx
- src/typescript/frontend/src/components/pages/home/components/main-card/MainCard.tsx
- src/typescript/frontend/src/components/pages/home/components/table-card/TableCard.tsx
- src/typescript/frontend/src/lib/queries/sorting/market-data.ts
- src/typescript/frontend/src/lib/queries/sorting/types.ts
- src/typescript/frontend/src/lib/routes/home-page-params.ts
Manual testing by clicking the filter/sort by options and seeing if data updates rapidly
> [ECO-1889] Resolve caching issues and make sorting/filtering work on short intervals

- src/typescript/frontend/src/components/header/constants.ts
- src/typescript/frontend/src/components/header/index.tsx
- src/typescript/frontend/src/router/routes.ts
This PR updates the header of the website.
See Vercel preview.
> [ECO-1805] update header

- src/typescript/frontend/src/components/selects/dropdown-menu/components/dropdown-menu-item/styled.tsx
- src/typescript/frontend/src/components/selects/dropdown-menu/index.tsx
- src/typescript/frontend/src/components/selects/dropdown-menu/styled.tsx
- src/typescript/frontend/src/components/selects/multiple-select/index.tsx
- src/typescript/frontend/src/components/selects/select/index.tsx
- src/typescript/frontend/src/components/selects/single-select/index.tsx
- src/typescript/frontend/src/components/selects/theme.ts
- src/typescript/frontend/src/components/selects/types.ts
- src/typescript/frontend/src/hooks/use-tooltip/index.tsx
This PR updates the filter tooltip on the main menu.
See Vercel deployment.
> [ECO-1797] update tooltip menu

- src/typescript/frontend/src/router/routes.ts
> [ECO-1898] update start here link

- src/typescript/frontend/src/components/header/index.tsx
- src/typescript/frontend/src/components/link/component.tsx
See title.
See Vercel preview.
> [ECO-1901] make start here button open a new tab

- cfg/cspell-frontend-dictionary.txt
- src/typescript/frontend/package.json
- src/typescript/frontend/src/app/home/page.tsx
- src/typescript/frontend/src/app/pools/api/route.ts
- src/typescript/frontend/src/components/pages/home/components/emoji-table/index.tsx
- src/typescript/frontend/src/components/pages/pools/ClientPoolsPage.tsx
- src/typescript/frontend/src/components/pages/pools/components/liquidity/index.tsx
- src/typescript/frontend/src/components/pages/pools/components/pools-table/components/table-row-desktop/types.ts
- src/typescript/frontend/src/components/pages/pools/components/pools-table/index.tsx
- src/typescript/frontend/src/components/pages/pools/components/table-header-switcher/index.tsx
- src/typescript/frontend/src/components/pages/pools/components/table-header-switcher/types.ts
- src/typescript/frontend/src/lib/queries/sorting/market-data.ts
- src/typescript/frontend/src/lib/queries/sorting/types.ts
- src/typescript/pnpm-lock.yaml
- src/typescript/sdk/src/queries/const.ts
This PR updates the pools page by adding:
> [ECO-1903] pools page updates

- src/typescript/frontend/src/components/pages/emojicoin/components/main-info/MainInfo.tsx
- src/typescript/frontend/src/components/pages/home/components/main-card/MainCard.tsx
- src/typescript/frontend/src/components/pages/home/components/table-card/TableCard.tsx
- src/typescript/frontend/src/components/pages/launch-emojicoin/ClientLaunchEmojicoinPage.tsx
- src/typescript/frontend/src/components/pages/pools/components/pools-table/components/table-row-desktop/index.tsx
- src/typescript/frontend/src/components/text/types.ts
- src/typescript/frontend/src/hooks/use-tooltip/styled.tsx
This PR updates the square section.
> [ECO-1818] square section updates

- src/typescript/frontend/src/app/home/loading.tsx
- src/typescript/frontend/src/app/launch/loading.tsx
- src/typescript/frontend/src/app/launch/page.tsx
- src/typescript/frontend/src/app/loading.tsx
- src/typescript/frontend/src/app/market/[market]/loading.tsx
- src/typescript/frontend/src/app/pools/loading.tsx
- src/typescript/frontend/src/app/verify/loading.tsx
- src/typescript/frontend/src/components/loading.tsx
- src/typescript/sdk/src/queries/candlestick.ts
- src/typescript/sdk/src/queries/chat.ts
- src/typescript/sdk/src/queries/liquidity.ts
- src/typescript/sdk/src/queries/state.ts
- src/typescript/sdk/src/queries/swap.ts
- src/typescript/sdk/src/queries/utils.ts
Optimize queries by not using `wrap` which will make postgres use indexes.
Also adds loading pages.
> [ECO-1927] optimize queries and add loading pages

- src/typescript/frontend/src/components/pages/pools/components/liquidity/index.tsx
- src/typescript/frontend/src/components/pages/pools/components/liquidity/styled.tsx
- src/typescript/frontend/src/utils/get-empty-list-tr.tsx
This PR updates the Pools page styling.
Noting that the responsive issue is fixed by ECO-1903.
See Vercel preview.
> [ECO-1902] Update pools page styling

- src/typescript/frontend/package.json
- src/typescript/frontend/src/components/footer/index.tsx
- src/typescript/frontend/src/components/svg/icons/LogoIcon.tsx
- src/typescript/frontend/src/lib/env.ts
- src/typescript/pnpm-lock.yaml
Add versioning and display a badge to show the version.
If this is a prerelease, an versioning badge will show up in the header, as well as the footer, near the emojicoin.fun logo, showing the prerelease type (alpha or beta), among with the running version.
If this is not a prerelease, a versioning badge will show up in the footer only, displaying the running version.
> [ECO-1954] update versioning

- src/typescript/frontend/src/components/wallet/LearnMoreSlideshow.tsx
Verify the words in the Aptos Connect modal are correct
> [ECO-1975] Fix typo/poor wording in Aptos Connect modal

- src/typescript/frontend/src/app/layout.tsx
- src/typescript/frontend/src/components/charts/ChartContainer.tsx
- src/typescript/frontend/src/components/charts/PrivateChart.tsx
- src/typescript/frontend/src/components/charts/README.md
- src/typescript/frontend/src/components/charts/const.ts
- src/typescript/frontend/src/components/emoji-picker/triangle.css
- src/typescript/frontend/src/components/pages/emojicoin/components/desktop-grid/index.tsx
- src/typescript/frontend/src/components/pages/emojicoin/components/mobile-grid/index.tsx
- src/typescript/frontend/src/components/pages/launch-emojicoin/hooks/use-register-market.ts
- src/typescript/frontend/src/components/svg/icons/LogoIcon.tsx
- src/typescript/frontend/src/context/wallet-context/AptosContextProvider.tsx
- src/typescript/frontend/src/lib/env.ts
- src/typescript/frontend/src/lib/store/event-store.ts
- src/typescript/frontend/src/lib/store/server-to-client/StoreOnClient.tsx
- src/typescript/frontend/src/lib/store/server-to-client/SubscribeToMarketRegistrations.tsx
- src/typescript/sdk/src/markets/utils.ts
> [ECO-1951] Chart updates

- src/typescript/frontend/src/app/market/[market]/page.tsx
- src/typescript/frontend/src/components/emoji-picker/triangle.css
- src/typescript/frontend/src/components/pages/home/components/main-card/MainCard.tsx
- src/typescript/frontend/src/components/pages/home/components/table-card/TableCard.tsx
- src/typescript/frontend/src/components/pages/launch-emojicoin/ClientLaunchEmojicoinPage.tsx
- src/typescript/frontend/src/lib/utils/emojis-to-name-or-symbol.ts
- src/typescript/frontend/src/middleware.ts
- src/typescript/frontend/src/utils/pathname-helpers.ts
Updates the market routing system:
- market names are defined by the name of the emojis as follows: the name of the market 🍑🍑 is `peach;peach`.
- a market is accessible via `/market/MARKET_NAME`
- going to `/market/EMOJIS` will redirect to `/market/MARKET_NAME`.
For example, when accessing `https://emojicoin.fun/market/🍑🍑`, you will get redirected to `https://emojicoin.fun/market/peach,peach`.
> [ECO-1667] update routing system

- cfg/cspell-dictionary.txt
- src/typescript/frontend/public/images/search-icon.svg
- src/typescript/frontend/src/app/global.css
- src/typescript/frontend/src/app/home/HomePage.tsx
- src/typescript/frontend/src/app/home/page.tsx
- src/typescript/frontend/src/app/market/api/route.ts
- src/typescript/frontend/src/app/page.tsx
- src/typescript/frontend/src/components/emoji-picker/EmojiPickerWithInput.tsx
- src/typescript/frontend/src/components/inputs/textarea/index.tsx
- src/typescript/frontend/src/components/pages/home/components/emoji-table/ClientGrid.tsx
- src/typescript/frontend/src/components/pages/home/components/emoji-table/components/FilterOptions.tsx
- src/typescript/frontend/src/components/pages/home/components/emoji-table/components/Search.tsx
- src/typescript/frontend/src/components/pages/home/components/emoji-table/components/buttons-block/index.tsx
- src/typescript/frontend/src/components/pages/home/components/emoji-table/components/buttons-block/styled.tsx
- src/typescript/frontend/src/components/pages/home/components/emoji-table/index.tsx
- src/typescript/frontend/src/components/pages/home/components/emoji-table/styled.tsx
- src/typescript/frontend/src/components/pages/home/components/main-card/MainCard.tsx
- src/typescript/frontend/src/components/pages/pools/ClientPoolsPage.tsx
- src/typescript/frontend/src/lib/queries/sorting/market-data.ts
- src/typescript/frontend/src/lib/queries/sorting/query-params.ts
- src/typescript/frontend/src/lib/routes/home-page-params.ts
- src/typescript/frontend/src/lib/store/input-store.ts
- src/typescript/pnpm-lock.yaml
- src/typescript/sdk/src/emoji_data/utils.ts
This PR adds the functionality to search for pools on the home page.
In order to make this process more usable, I made the home page hybrid.
It will use the props provided by the server to display the initial page. But
then, instead of refreshing the page whenever new data needs to be fetched, it
will be fetched dynamically.
See vercel.
> [ECO-1972] add search on home page

- src/typescript/frontend/src/components/pages/emojicoin/components/chat/components/message-container/index.tsx
- src/typescript/frontend/src/utils/parse-changes-for-balances.ts
> [ECO-2001] Increase emoji chat text size

- src/typescript/frontend/src/router/routes.ts
This PR updates the start here link.
See vercel and check that when you click on start here you are redirected to https://docs.emojicoin.fun/category/--start-here
> [ECO-1976] Update start here link

- README.md
- src/typescript/frontend/playwright.config.ts
- src/typescript/frontend/src/app/test/route.ts
- src/typescript/frontend/src/lib/store/event-utils.ts
- src/typescript/frontend/tests/e2e/example.spec.ts
- src/typescript/sdk/src/utils/misc.ts
> [ECO-2077] Create a `production` branch for the production environment, add a `README`

- src/typescript/sdk/src/markets/utils.ts
Pretty self explanatory, just removing a function that accidentally got merged in.
> [ECO-2162] Remove `sleep` function that snuck into the grace period flag check

- doc/doc-site/docs/about/how-it-works.md
Link to the blackpaper on the docs site.
See CI preview.
> [ECO-2198] Link to blackpaper on docs site

- src/typescript/frontend/src/components/info/index.tsx
- src/typescript/frontend/src/components/pages/launch-emojicoin/memoized-launch/index.tsx
On the pools page:
This PR moves the "i" icon to the left of the text and keeps the right alignment.
It also makes it slightly smaller.
See vecrel.
> [ECO-2204] Update "i" icon design on launch page

- src/cloud-formation/deploy-main.yaml
Bump container versions for assorted recent changes
e2e testing done on assorted local stacks and affiliated PRs
> [ECO-2251] Bump indexer processor, broker versions

- .github/workflows/pre-commit.yaml
- cfg/pre-commit-config.yaml
- src/typescript/frontend/package.json
- src/typescript/sdk/package.json
This PR adds js/ts linting to pre-commit.
> [ECO-2244] Add js/ts linting to pre-commit

- src/typescript/frontend/src/components/emoji-picker/EmojiPickerWithInput.tsx
- src/typescript/frontend/src/components/pages/home/components/emoji-table/ClientGrid.tsx
- src/typescript/frontend/tests/e2e/market-order.spec.ts
- src/typescript/frontend/tests/e2e/search.spec.ts
This PR adds an e2e test for the home page sorting.
> [ECO-2153] Add sorting e2e tests

- src/typescript/frontend/src/components/pages/home/components/emoji-table/index.tsx
- src/typescript/frontend/src/components/pages/home/components/table-card/TableCard.tsx
- src/typescript/frontend/src/lib/queries/sorting/query-params.ts
This PR fixes various small bugs inside atomic commits. See commits name for more details.
> [ECO-2370] Fix small bugs

- src/typescript/frontend/src/app/global.css
- src/typescript/frontend/src/components/pages/home/components/emoji-table/components/buttons-block/index.tsx
- src/typescript/frontend/src/components/pages/home/components/emoji-table/index.tsx
This PR adds navigation buttons at the top of the market grid to facilitate navigation.
See vercel preview, home page.
> [ECO-2383] Add pagination navigation at the top of the market grid

- src/cloud-formation/indexer.cfn.yaml
This PR enables Performance Insights to make it easier to diagnose DB bottlenecks.
> [ECO-2395] Enable Performance Insights for DB

- src/typescript/frontend/src/lib/store/event/event-store.ts
- src/typescript/frontend/src/lib/store/event/local-storage.ts
- src/typescript/frontend/src/lib/store/event/utils.ts
- src/typescript/frontend/tsconfig.json
- src/typescript/types.ts
Clean up `ECO-2404`, this PR exists to make the diff and blame more clear.
> [ECO-2416] Clean up `ECO-2404`

- src/typescript/frontend/src/app/home/page.tsx
Cache requests to the aptos node.
Run locally, check cache folder.
> [ECO-2427] Cache num of markets query

- src/typescript/frontend/src/app/launching/page.tsx
- src/typescript/frontend/src/lib/server-env.ts
- src/typescript/frontend/src/middleware.ts
- src/typescript/frontend/src/router/routes.ts
> [ECO-2435] Add pre launch page

- src/move/emojicoin_dot_fun/Move.toml
- src/move/emojicoin_dot_fun/sources/emojicoin_dot_fun.move
1. Lower the refundable deposit amount
2. Bump the Move package version
```sh
cd src/move/emojicoin_dot_fun
```
```sh
aptos move test --dev
```
All tests pass
> [ECO-2445] Lower refundable deposit amount, bump version

- doc/doc-site/docs/about/how-it-works.md
- doc/doc-site/docs/resources/faq.md
SSIA: Change all references of 4 APT deposit to 1 APT in the docs.
> [ECO-2452] Change all references of 4 APT deposit to 1 APT in the docs

- src/typescript/frontend/src/app/market/[market]/page.tsx
- src/typescript/frontend/src/lib/queries/aptos-client/market-view.ts
Merge `serialization` and `cache` market view fix to `production`
Tested in preview build in #387
> [ECO-2457] Merge `serialization` and `cache` market view fix to `production`

- src/typescript/frontend/src/components/pages/emojicoin/components/trade-emojicoin/SwapComponent.tsx
- src/typescript/frontend/src/lib/hooks/queries/use-simulate-swap.ts
> [ECO-2463] Separate the actual txn simulation for gas usage calculation from the swap output calculation

- src/typescript/frontend/src/components/pages/emojicoin/components/trade-emojicoin/SwapComponent.tsx
- src/typescript/frontend/src/lib/hooks/queries/use-simulate-swap.ts
Merge `main` to `production` to add a cached swap simulation and a cached gas cost.
Preview build testing with this PR.
> [ECO-2464] Merge `main` to `production` (cached swap simulation + gas cost)

- src/typescript/frontend/src/lib/hooks/queries/use-wallet-balance.ts
- src/typescript/sdk/src/emojicoin_dot_fun/aptos-framework.ts
- src/typescript/sdk/src/emojicoin_dot_fun/index.ts
> [ECO-2490] Merge `main` to `production` for the balance query fix

- src/typescript/frontend/src/components/pages/home/components/emoji-table/utils.ts
- src/typescript/frontend/src/components/pages/home/components/table-card/TableCard.tsx
Tested in preview build on testnet and on mainnet
> [ECO-2491] Merge the 24h volume + "Last Swap" fix to `production`

- src/typescript/frontend/src/configs/index.ts
- src/typescript/frontend/src/configs/local-storage-keys.ts
- src/typescript/frontend/src/context/language-context/helpers.ts
- src/typescript/frontend/src/context/theme-context/index.tsx
- src/typescript/frontend/src/hooks/use-is-user-geoblocked.ts
- src/typescript/frontend/src/utils/index.ts
Cache VPN queries using local storage.
> [ECO-2483] Cache VPN queries

- src/typescript/example.env
- src/typescript/frontend/package.json
- src/typescript/frontend/src/app/verify_status/page.tsx
- src/typescript/frontend/src/components/header/components/mobile-menu/index.tsx
- src/typescript/frontend/src/components/header/wallet-button/ConnectWalletButton.tsx
- src/typescript/frontend/src/components/pages/emojicoin/components/main-info/MainInfo.tsx
- src/typescript/frontend/src/components/pages/verify/VerifyPage.tsx
- src/typescript/frontend/src/components/pages/verify_status/VerifyStatusPage.tsx
- src/typescript/frontend/src/components/svg/icons/NightlyIcon.tsx
- src/typescript/frontend/src/components/wallet/toasts.tsx
- src/typescript/frontend/src/configs/local-storage-keys.ts
- src/typescript/frontend/src/context/wallet-context/WalletItem.tsx
- src/typescript/frontend/src/hooks/use-is-user-geoblocked.ts
- src/typescript/frontend/src/lib/queries/sorting/query-params.ts
- src/typescript/frontend/src/lib/server-env.ts
- src/typescript/frontend/src/lib/utils/explorer-link.ts
- src/typescript/frontend/src/utils/geolocation.ts
- src/typescript/pnpm-lock.yaml
- src/typescript/sdk/src/utils/misc.ts
#416 Nightly wallet
#421 Vercel headers to get location
#419 Add explorer link to market page
#429 Fix market cap sort bug due to default bump order
#428 Remove arrow in connect button
Closes #426
> [ECO-2527] Merge market cap sort bug fix to `production` (plus other changes)

- src/typescript/sdk/package.json
Not sure how detailed we want to support a release log or changeset yet as it is going to move very quickly.
> [ECO-2569] Bump SDK release version

- src/typescript/frontend/src/components/pages/emojicoin/components/trade-emojicoin/InputLabels.tsx
- src/typescript/frontend/src/components/pages/pools/components/liquidity/index.tsx
This PR fixes the styiling on mobile on the pool page.
See pool page on mobile.
> [ECO-2413] Fix pool page mobile styling

- src/docker/deployer/Dockerfile
- src/docker/deployer/sh/build-publish-payloads.sh
- src/docker/deployer/sh/entrypoint.sh
> [ECO-2592] Update `deployer` dockerfile and scripts to incorporate the new `market_metadata` module

- src/move/market_metadata/README.md
This PR adds documentation for adding and removing admins in the market metadata module.
Run documented commands.
> [ECO-2597] Document adding/removing admins process

- src/move/rewards/README.md
Update rewards README for claim link archival.
Read it and weep
> [ECO-2441] Update rewards README

- src/typescript/frontend/package.json
> [ECO-2560] Bump frontend version to 1.0.0

- src/typescript/example.env
- src/typescript/frontend/src/components/button/index.tsx
- src/typescript/frontend/src/components/pages/emojicoin/components/main-info/MainInfo.tsx
- src/typescript/frontend/src/lib/env.ts
This PR adds a hover message to tell the user how to set the social links.
Go to a market page and hover on the disabled social links.
> [ECO-2614] Add message to indicate how to get socials on the market page

- src/move/market_metadata/README.md
This PR adds information on the special properties used by the frontend in the market metadata readme. It also fixes some previously documented commands.
Deploy on devnet and run the commands from the readme.
> [ECO-2634] Complete market metadata readme

- src/typescript/frontend/src/components/pages/emojicoin/components/main-info/MainInfo.tsx
This PR updates the on hover popup message for the market page metadata.
See vercel.
> [ECO-2635] Change metadata hover message

- src/typescript/example.env
This PR adds documentation for setting up the CDN.
> [ECO-2648] Add CDN documentation

- src/typescript/sdk/package.json
Change `Econia's` to `Econia Labs'` in the TS SDK description
> [ECO-2654] Update SDK description with Econia Labs

- doc/doc-site/docs/about/about.md
- doc/doc-site/docusaurus.config.js
- doc/doc-site/package.json
- doc/doc-site/pnpm-lock.yaml
1. Follow official instructions at https://docusaurus.io/docs/markdown-features/math-equations to fix LaTeX
1. Link to package addresses on home page
Local build passes, see Vercel preview
> [ECO-2668] Fix LaTeX, add package addresses to docs site

- src/typescript/frontend/package.json
- src/typescript/sdk/package.json
> [ECO-2681] Bump sdk/frontend release versions

- src/typescript/sdk/src/const.ts
Self explanatory
Builds shouldn't fail if this works.
> [ECO-2773] Add `release-preview` to the list of `VERCEL_TARGET_ENV` values possible

- .github/workflows/submodule.yaml
Update processor submodule GitHub Actions check to work with `emojicoin-arena` and `arena` branches
Will kinda just need to be tested and fixed if it's broken
> [ECO-2796] Update processor submodule GitHub Actions check to work with `emojicoin-arena` and `arena` branches

- src/typescript/frontend/public/community-projects.json
- src/typescript/frontend/src/app/cult/page.tsx
Fairly self explanatory.
Check it works in the preview build (since it's no longer feature gated)
> [ECO-2797] Update `community-projects.json` with an example and turn off feature gate

- src/typescript/frontend/src/components/pages/home/components/emoji-table/components/buttons-block/index.tsx
Changes nothing functionally- just cleans up the component. I noticed it while doing something else- figured I'd clean it up really quickly.
> [ECO-2799] Clean up buttons block component

- src/typescript/frontend/src/router/routes.ts
> [ECO-2802] Fix minor import issue

- src/typescript/frontend/package.json
> [ECO-2792] Bump frontend version for release

- src/typescript/frontend/src/app/arena/positions/[address]/route.ts
- src/typescript/frontend/src/components/pages/arena/ArenaClient.tsx
- src/typescript/frontend/src/components/pages/arena/tabs/EnterTab.tsx
- src/typescript/frontend/src/components/pages/arena/tabs/ProfileTab.tsx
- src/typescript/frontend/src/components/pages/arena/utils.tsx
- src/typescript/sdk/src/indexer-v2/queries/app/arena.ts
- src/typescript/sdk/src/indexer-v2/types/index.ts
- src/typescript/sdk/src/indexer-v2/types/json-types.ts
- src/typescript/sdk/src/types/arena-types.ts
This PR updates the SDK to conform with the new schema changes made in the processor refactor.
> [ECO-2815] Update SDK according to processor changes

- src/typescript/frontend/package.json
- src/typescript/sdk/package.json
> [ECO-2820] Bump frontend/SDK versions

- src/typescript/frontend/public/community-projects.json
Add the hairclub telegram bot to `community-projects.json`
> [ECO-2818] List HAIR JSON data

- src/typescript/frontend/src/app/layout.tsx
- src/typescript/frontend/src/components/misc/background-emojis/BackgroundEmojis.tsx
The hover on blur was non-performant and a UX issue. Remove it and clean up the rest of the component code.
Tested locally manually.
> fix(ECO-2846): Remove the blur on hover effect for performance and UX reasons

- src/typescript/sdk/tests/e2e/arena/general/arena.test.ts
This PR adds more E2E tests for the arena processor.
> test(ECO-2826): Add happy path indexer testing for enter, swap, and exit

- src/typescript/sdk/tests/e2e/arena/general/arena.test.ts
This PR adds even more E2E tests for the arena processor.
> test(ECO-2827): Add arena leaderboard testing

- README.md
- doc/doc-site/docs/resources/audit.md
Document the `emojicoin arena` audit in the repo README and in the docs site
CI docs site build
> docs(ECO-2860): Document emojicoin arena audit

- .github/PULL_REQUEST_TEMPLATE.md
Simplify the PR template since the removed items are covered by conventional commits
CI passes locally
> chore(ECO-2880): Simplify PR template for conventional commits

- src/typescript/frontend/src/components/pages/arena/ArenaClient.tsx
- src/typescript/frontend/src/components/pages/arena/PriceChart.tsx
- src/typescript/frontend/src/components/pages/arena/tabs/EnterTab.tsx
- src/typescript/frontend/src/components/pages/arena/tabs/index.tsx
- src/typescript/frontend/src/components/pages/arena/utils.tsx
Miscellaneous code clean-up and stylistic fixes for consistency- this changes nothing at all about the code functionally.
This doesn't change anything about the code functionally
> chore(ECO-2875): Miscellaneous clean-up and stylistic fixes for consistency

- src/typescript/frontend/src/components/pages/emojicoin/components/desktop-grid/index.tsx
- src/typescript/frontend/src/components/pages/emojicoin/components/holders/coin-holders.tsx
- src/typescript/frontend/src/components/pages/emojicoin/components/mobile-grid/index.tsx
- src/typescript/frontend/src/components/pages/emojicoin/components/trade-history/trade-history.tsx
- src/typescript/frontend/src/components/pages/wallet/WalletClientPage.tsx
- src/typescript/frontend/src/components/ui/table/ecTable.tsx
- src/typescript/frontend/src/components/ui/table/ecTableBody.tsx
- src/typescript/frontend/src/components/ui/table/ecTableRow.tsx
- src/typescript/frontend/src/components/ui/table/table.tsx
This also includes the change to the header title for "amount" into the emojicoin.
> fix(ECO-2900) Fill table with empty rows when there is not enough items

- src/typescript/frontend/public/community-projects.json
Add `emojirocket100` data to the cult creations page
See preview
> chore(ECO-2916): Update community-projects.json with emojirocket100 data

- src/typescript/frontend/public/community-projects.json
> chore(ECO-2927): Add red envelope bot to `community-projects.json`

- src/typescript/sdk/tests/e2e/arena/general/arena.test.ts
This PR adds more complete testing to the arena indexing.
> test(ECO-2862): Add missing test cases for arena processing

- src/typescript/sdk/src/indexer-v2/queries/app/arena.ts
- src/typescript/sdk/src/indexer-v2/types/index.ts
Very straightforward- just a small fix to standardize addresses and fix an import.
> fix(ECO-2944): Standardize account addresses in arena queries; fix import

- src/typescript/sdk/src/indexer-v2/queries/app/arena.ts
- src/typescript/sdk/src/indexer-v2/types/index.ts
- src/typescript/sdk/src/indexer-v2/types/json-types.ts
- src/typescript/sdk/src/types/arena-types.ts
- src/typescript/sdk/tests/e2e/arena/candlesticks.test.ts
- src/typescript/sdk/tests/e2e/arena/general.test.ts
- src/typescript/sdk/tests/e2e/arena/utils.ts
This PR updates the SDK with the latest processor changes
> chore(ECO-2925): Update SDK and related tests

- src/typescript/sdk/tests/e2e/arena/candlesticks.test.ts
- src/typescript/sdk/tests/e2e/arena/general.test.ts
This PR ensures all the data is correct when a melee swap happens after that melee has ended.
> test(ECO-2934): Test swap after crank edge case

- src/typescript/frontend/src/components/charts/trading-view-utils.ts
- src/typescript/frontend/src/components/pages/home/components/arena-card/index.tsx
- src/typescript/frontend/src/router/routes.ts
> fix(ECO-2986): Format/lint all arena changes, remove merge conflict message from `routes.ts`

- src/typescript/frontend/public/community-projects.json
adding anime invader to website
> chore(ECO-3022): Add anime invader to community-projects.json

- src/typescript/sdk/package.json
- src/typescript/sdk/src/client/emojicoin-client.ts
Using it with my custom scripts
> fix(ECO-3033): Fix the exported types in the SDK

- src/typescript/frontend/src/app/arena/page.tsx
- src/typescript/frontend/src/components/charts/const.ts
- src/typescript/frontend/src/components/pages/arena/ArenaClient.tsx
- src/typescript/frontend/src/components/pages/arena/utils.tsx
- src/typescript/frontend/src/lib/store/event/candlestick-bars.ts
- src/typescript/frontend/src/lib/store/event/event-store.ts
- src/typescript/frontend/src/lib/store/event/types.ts
- src/typescript/frontend/src/lib/store/event/utils.ts
- src/typescript/sdk/src/indexer-v2/types/index.ts
> chore(ECO-3043): Misc cleanup, remove unused functions, simplify/fix db model type guards [3.1/4]

- src/typescript/frontend/src/components/pages/arena/tabs/InfoTab.tsx
This PR updates the placeholder text in the arena info tab to a meaningful q&a.
> docs(ECO-3017): Add arena documentation in the arena info tab

- .github/workflows/tests.yaml
- src/typescript/package.json
- src/typescript/sdk/package.json
- src/typescript/sdk/tests/e2e/arena/candlesticks.test.ts
- src/typescript/sdk/tests/e2e/arena/general.test.ts
- src/typescript/sdk/tests/e2e/arena/utils.ts
- src/typescript/sdk/tests/e2e/candlesticks.test.ts
- src/typescript/sdk/tests/e2e/helpers/misc.ts
- src/typescript/turbo.json
This PR adds E2E tests for the new candlesticks.
> test(ECO-3051): Add candlesticks test to E2E suite

- src/typescript/frontend/src/lib/env.ts
- src/typescript/frontend/src/lib/server-env.ts
- src/typescript/frontend/src/middleware.ts
> chore(ECO-3087): Clean up rate limiter env var loading, don't load if it's disabled

- src/typescript/frontend/src/app/wallet/[address]/error.tsx
- src/typescript/frontend/src/app/wallet/[address]/page.tsx
- src/typescript/frontend/src/app/wallet/utils.ts
- src/typescript/frontend/src/lib/hooks/queries/use-fetch-owner-emojicoin-balances.ts
- src/typescript/frontend/src/middleware.ts
- src/typescript/sdk/src/utils/validation/ans-name.ts
- src/typescript/sdk/tests/unit/ans-validation.test.ts
This PR fixes the ANS regex.
It was missing the suffix (e.g. `.apt`/`.petra`).
> fix(ECO-3095): Fix ANS regex

- cfg/cspell-dictionary.txt
- src/typescript/frontend/src/components/pages/arena/tabs/InfoTab.tsx
1. Update the copy on the emojicoin arena info tab
1. Add gamified to cspell dictionary
See preview deployment
> docs(ECO-3135): Update emojicoin arena how it works copy

- doc/doc-site/docs/about/core-values.md
- doc/doc-site/docs/about/emojicoin-LP.md
- doc/doc-site/docs/about/how-it-works.md
- doc/doc-site/docs/resources/faq.md
- doc/doc-site/docs/resources/glossary.md
- doc/doc-site/docs/start-here/aptos-wallet-and-cex.md
- doc/doc-site/docs/start-here/aptos-wallet-and-moonpay.md
- doc/doc-site/docs/start-here/bridging-from-eth.md
- doc/doc-site/docs/start-here/how-to-trade-on-emojicoin.md
Make assorted stylistic changes to the docs site
> chore(ECO-3138): Update docs site

- doc/doc-site/docs/about/about.md
This PR adds the arena package address to the doc site.
> docs(ECO-3130): Add arena package address to the docs site

- doc/doc-site/docs/resources/integrators/api/geckoterminal.md
- doc/doc-site/sidebar.js
This PR adds documentation for the GeckoTerminal API.
> docs(ECO-3081): Add GeckoTerminal docs

- src/move/emojicoin_arena/README.md
Add a command that shows cranking via the CLI
https://explorer.aptoslabs.com/txn/6679772881/userTxnOverview?network=testnet
> docs(ECO-3197): Add crank CLI command

- src/typescript/frontend/package.json
Bump the frontend version minor
CI
> chore(ECO-3193): Bump frontend version minor

- src/typescript/frontend/package.json
- src/typescript/frontend/src/components/pages/arena/tabs/enter-tab/EnterTabLockPhase.tsx
This PR updates the placeholder matching algorithm with the correct one.
In progress.
> fix(ECO-3200): Implement correct matching algorithm

- src/typescript/frontend/package.json
- src/typescript/frontend/src/components/pages/arena/tabs/enter-tab/EnterTabLockPhase.tsx
- src/typescript/frontend/src/components/pages/arena/tabs/enter-tab/MatchAmount.tsx
- src/typescript/frontend/src/components/pages/arena/tabs/utils.tsx
> chore(ECO-3210): Merge `production` to `main` (UI arena fixes); #796 -#797

- doc/doc-site/docs/about/about.md
This PR adds the mainnet arena address to the doc site.
> docs(ECO-3206): Add arena mainnet address to doc site

- src/typescript/frontend/package.json
Bumps the frontend version to 1.8.2
> chore(ECO-3216): Bump frontend version to 1.8.2

- doc/doc-site/docs/about/about.md
- src/typescript/frontend/package.json
- src/typescript/frontend/src/app/api/geckoterminal/pair/route.ts
- src/typescript/frontend/src/components/charts/get-bars.ts
- src/typescript/frontend/src/components/charts/use-datafeed.ts
- src/typescript/frontend/src/lib/dexscreener/routes.ts
- src/typescript/frontend/src/lib/store/arena/event/utils.ts
- src/typescript/frontend/src/lib/store/event/candlestick-bars.ts
- src/typescript/frontend/src/lib/store/event/event-store.ts
- src/typescript/frontend/src/lib/store/event/types.ts
- src/typescript/sdk/src/indexer-v2/queries/app/dexscreener.ts
- #799 
- #801 
- #802 
- #803
> chore(ECO-3217): Merge `main` to `production`; PRs #799 - #803

- src/typescript/frontend/src/components/pages/emojicoin/components/trade-history/trade-history.tsx
Replace txn version with marketNonce as key for list items
> fix(ECO-3238): Fix duplicate key issue on market page

- src/typescript/frontend/public/community-projects.json
Add Art Shrine from Aptos Weebs, where you need some emojicoins to participate and get some rewards!
Also the best reward is to improve your art skills ;)
> feature(ECO-3263): Add Art Shrine to cult page
