- doc/blackpaper/calculations.py
- doc/blackpaper/main.tex
- src/move/.gitignore
- src/move/sources/emojicoin_dot_fun.move
- src/python/move_emojis/scripts/generate_code.py
Generally, this PR adds swap simulation and commitment functionality for updating economic variables. Move code changes are awaiting integration with coin types. Some integrations, for example minting LP coins, are pending #10, and are captured in ECO-1567
Blackpaper changes:
1. Update precision support, derivations, for revised economic variables per 3347bd9
1. Fix assorted typos
1. Extend calculations script to autogen Move code
Move stylistic changes:
1. Remove unused max coin name length constant that is unlikely to be used elsewhere
1. Line break Move code at 100 chars per contributions guideline per Move book
1. Consolidate test-only `use` statements at top of module for ease of linked module analysis
1. Lookup markets by address rather than by `Object<Market>` to avoid extra …
> [ECO-1546] Add swap func stubs

- src/move/emojicoin_dot_fun/sources/emojicoin_dot_fun.move
- src/move/emojicoin_dot_fun/sources/hex_codes.move
Add at market level:
1. Cumulative base volume
1. Cumulative quote volume
Add at global level, via aggregators (for parallelism):
1. Total quote locked
1. Cumulative quote volume
Housekeeping:
1. Fix an inconsistent instance of type args
1. Remove redundant type annotations
1. Replace `input_is_base` to more intuitive `is_sell`
```sh
git ls-files | entr -c aptos move test --package-dir src/move/emojicoin_dot_fun --dev
```
> [ECO-1585] Add volume/TVL tracking, housekeeping

- src/move/emojicoin_dot_fun/sources/emojicoin_dot_fun.move
Core logic:
1. Abstract `GlobalStats` resource
1. Add market cap and FDV to tracked global stats
1. Update swap function to globally aggregate FDV/market cap effects
Housekeeping:
1. Make registry a named object
1. Remove a redundant type annotation
```sh
git ls-files | entr -c aptos move test --dev --package-dir src/move/emojicoin_dot_fun
```
> [ECO-1592] Add global FDV, market cap tracking

- .gitignore
- doc/architecture-specification.md
- src/move/emojicoin_dot_fun/sources/emojicoin_dot_fun.move
1. Track local fees for integrator, pool base, pool quote
1. Track global integrator fees
1. Add helpers for calculating TVL in CLAMM and CPAMM
1. Aggregate TVL globally, via changes in swap and liquidity functions
Housekeeping
1. Take out emojicoin monospace on architecture specification where not
applicable
1. Clear out gitignore at top level since not needed
1. Sort uses, constants
```sh
git ls-files | entr -c aptos move test --dev --package-dir src/move/emojicoin_dot_fun
```
> [ECO-1593] Add TVL, fee aggregation locally and globally

- .github/PULL_REQUEST_TEMPLATE.md
- doc/architecture-specification.md
- src/move/emojicoin_dot_fun/sources/emojicoin_dot_fun.move
1. Abstract existing data structures for stats
1. Create new state events for tracking indexed data
1. Create `init_module_for_testing()` helper
1. Incorporate global and local backend-less indexing, to rely solely on GraphQL
endpoint
1. Update architecture specification for designs
1. Update tests to incorporate timestamp support
1. Add chat API/event stubs
```sh
git ls-files | entr -c aptos move test --dev --package-dir src/move/emojicoin_dot_fun
```
> [ECO-1609] Add periodic/instantaneous state events, chat stubs

- src/typescript/api/src/emojicoin_dot_fun/utils.ts
- src/typescript/api/tests/e2e/register.test.ts
The new `emojicoin_dot_fun.move` has differently structured resources. We need to update the types in the typescript unit tests to reflect this accurately so the unit tests/CI will not fail.
`pnpm run test` and the CI unit tests
> [ECO-1613] Fix Market resource query for CI/unit test

- src/typescript/frontend/package.json
Because react-scripts thinks it must have typescript v3 or v4, it complains that we're using v5. According to this issue:
https://github.com/facebook/create-react-app/issues/13080
Typescript v5 works just fine with Create React App (CRA). Thus we can override it in package.json.
```shell
npm install && npm run build && npm run start
```
Tested locally for now.
> [ECO-1615] Fix peer dependency with react-scripts with override in package.json

- doc/architecture-specification.md
- src/move/emojicoin_dot_fun/sources/emojicoin_dot_fun.move
- src/move/emojicoin_dot_fun/sources/tests.move
1. Since the [coverage tool is broken for inline functions][coverage tool], take
out all inline annotations except where:
1. The function returns a borrowed reference.
1. The function would require an `acquires` statement if not inline.
1. Add swap/buy trigger differentiation on swaps.
1. Track market-wise Aptos Coin balance in a `MarketView`.
1. Update initial market stats/state triggers.
1. Update tracking for market registration fees.
1. Add inline FDV helper function.
1. Fix start time/period return mismatch in periodic state tracker decoder.
1. Add assorted decoders for test-only state to main module.
1. Add struct mocking with base values, and struct-wise assertion.
1. Add tests to assert all state (global storage, emitted events) modifications
during package publication and market …
> [ECO-1629] Test module/market init to 100% coverage

- cfg/cspell-dictionary.txt
- src/move/emojicoin_dot_fun/sources/emojicoin_dot_fun.move
- src/move/emojicoin_dot_fun/sources/tests.move
1. Update registry nonce to increment at the beginning of the periodic state
trigger function.
1. Fix boolean check for if a swap ends in bonding curve.
1. Fix reserve amounts assignment statement.
1. Add decoder for unpacking a `Swap` struct, since the event is returned via
the swap simulator view function.
1. Add assorted minimal test-only functions such that testing can be contained
in testing file.
1. Clarify mock structure/testing function layout.
1. Change `TestStruct` pattern to `MockStruct` for clarity.
1. Add simple buy/exact state transition harnessing for swap function.
1. `bps_fee_assorted`
1. `simple_buy_amounts`
1. `swap_simple_buy`
1. `swap_exact_transition`
From in `src/move/emojicoin_dot_fun`
```sh
```
Compare …
> [ECO-1640] Add swap test setup harnessing for simple buy/exact transition cases

- src/typescript/api/.eslintrc.js
- src/typescript/api/src/emojicoin_dot_fun/consts.ts
- src/typescript/api/src/emojicoin_dot_fun/emojicoin-dot-fun.ts
- src/typescript/api/src/emojicoin_dot_fun/events.ts
- src/typescript/api/src/emojicoin_dot_fun/payload-builders.ts
- src/typescript/api/src/emojicoin_dot_fun/types.ts
- src/typescript/api/src/emojicoin_dot_fun/utils.ts
- src/typescript/api/src/markets/coin-transfers.ts
- src/typescript/api/src/markets/get-random-emoji.ts
- src/typescript/api/src/markets/trade.ts
- src/typescript/api/src/markets/trader.ts
- src/typescript/api/src/markets/utils.ts
- src/typescript/api/src/types/contract.ts
- src/typescript/api/src/types/core.ts
- src/typescript/api/src/types/index.ts
- src/typescript/api/tests/e2e/register.test.ts
- src/typescript/api/tests/utils/publish.ts
Most changes are in `src/typescript/api/src`
Also adds the basic mock data buy script in `markets/trade.ts`, creates hundreds of traders, funds them, and has them all buy the same coin. Easiest way to run it is with:
```shell
npx tsx markets/trade.ts
```
Updated `register.test.ts` to reflect new type names.
```shell
pnpm jest
```
> [ECO 1672] Add basic mock data buy script and types for queries/events

- src/move/emojicoin_dot_fun/sources/emojicoin_dot_fun.move
- src/move/emojicoin_dot_fun/sources/tests.move
1. Simplify liquidity provision error codes that can be handled via coin balance
checks.
1. Offload truncation effects onto LP providers for base provision amount via
round-up bitmask.
1. Add liquidity event decoder.
1. Update liquidity provide/remove functions to update global stats for FDV &
market cap, to prevent the accumulation of rounding errors.
1. Update liquidity provision/remove epilogue to reduce redundant calculation of
values.
1. Sort `&signer` to be first argument in public entry functions, with
corresponding address first in associated view functions.
1. Alphabetize test helper functions.
1. Incorporate Liquidity event mocking.
1. Incorporate liquidity provision helper functions.
1. Alphabetize some tests as needed.
1. FDV, market cap, TVL function validation.
1. Liquidity …
> [ECO-1661] Test provide/remove liquidity operations to 100% coverage

- cfg/cspell-dictionary.txt
- src/move/emojicoin_dot_fun/sources/emojicoin_dot_fun.move
- src/move/emojicoin_dot_fun/sources/tests.move
1. Update chat API to list market address second for consistency with other
APIs.
1. Add missing tracking for number of chat messages in a periodic state tracker.
1. Consolidate loopwise emoji chat operations to minimize gas costs.
1. Add checks on index validity, empty message for chat operations.
1. Parallelize registry nonce.
1. Update assert helpers for parallelized registry nonce.
1. Assorted chat expected failure tests.
1. Chat full state assertion test.
1. Update `chat_complex_emoji_sequences` to also verify assorted state
mutations, thusly renaming to `chat_complex`.
1. Escape `parallelizable` from spellchecker.
From in `src/move/emojicoin_dot_fun`
```sh
```
Compare coverage against bytecode:
```sh
aptos move coverage …
```
> [ECO-1673] Test chat to 100% coverage, parallelize registry nonce

- src/typescript/api/src/emojicoin_dot_fun/emojicoin-dot-fun.ts
- src/typescript/api/tests/e2e/chat.test.ts
- src/typescript/api/tests/e2e/register.test.ts
The `market_address` function argument position changed, so we must update the TS api to reflect this.
Also, in unit tests, previously, the publisher was registering multiple markets at the same time, which would often result in the `Transaction is already in mempool` error.
Unit tests in the TS api
> [ECO 1686] Update TS API calls to reflect new function signatures, fix e2e `Transaction in mempool` error

- src/typescript/api/jest.config.js
- src/typescript/api/package.json
- src/typescript/api/tests/e2e/register.test.ts
`cd src/typescript/api && pnpm jest`
> [ECO-1694] Fix jest serialization error and `marketID` check in e2e tests

- src/move/emojicoin_dot_fun/sources/emojicoin_dot_fun.move
- src/move/emojicoin_dot_fun/sources/tests.move
Test package to 100% coverage
1. Update test-only decoder for `PeriodicStateMetadata` to return fields in
same order as struct definition.
1. Add helpers functions for asserting an ongoing sequence of periodic state
events.
1. Add helper functions for getting TVL to LP coin ratio and TVL per LP coin
growth over a period.
1. Struct packer for `TVLtoLPCoinRatio` for ease of testing.
1. Complex triggers test.
1. Assorted expected failure tests.
1. Supplemental chat emoji tests.
1. Invalid coin type failure mode tests.
1. Assorted market metadata getter helpers.
1. Verified emoji failure tests.
1. Remove redundant type annotations for vectors.
From in `src/move/emojicoin_dot_fun`
```sh
```
Compare coverage against bytecode:
```sh
aptos …
```
> [ECO-1685] Test package to 100% coverage

- doc/move/emojicoin_dot_fun/emojicoin_dot_fun.md
- src/move/emojicoin_dot_fun/Move.toml
- src/move/emojicoin_dot_fun/sources/emojicoin_dot_fun.move
1. Make package immutable
1. Uncomment the `inline` keyword which was commented out during development,
such that 100\% coverage could be achieved. See
https://github.com/aptos-labs/aptos-core/issues/9154 for more.
1. Re-build docs.
All tests still pass, but now at 95.94\% coverage compared with 100% before uncommenting `inline` keyword.
From in `src/move/emojicoin_dot_fun`:
```sh
```
Published on testnet under single signer account:
https://explorer.aptoslabs.com/account/0xb11b48d9e8cece3b50a48996704bd1476caa761dfb84de38f9f8d1e136c8fa89/modules/code/emojicoin_dot_fun?network=testnet
Multisig account:
https://explorer.aptoslabs.com/account/0x761e2d91c9e986557b04bdda55b6b8ccf72402ec3b6681504c29f12a55d45e69/modules/code/emojicoin_dot_fu …
> [ECO-1564][Coverage] Make package immutable, uncomment `inline` keyword

- doc/move/emojicoin_dot_fun/emojicoin_dot_fun.md
- src/move/emojicoin_dot_fun/sources/emojicoin_dot_fun.move
1. Uncomment `inline` keyword per https://github.com/aptos-labs/aptos-core/issues/9154
1. Rebuild docs
From in src/move/emojicoin-dot-fun:
```sh
```
> [ECO-1756][Coverage][Audit] Uncomment `inline` keyword per 100% coverage

- src/typescript/sdk/tests/utils/generate-mock-data.ts
This PR fixes a bug where the candlesticks events would be inserted into the wrong table.
It also fixes the address of the generated periodic state events.
Run mock data script and check rest api for periodic state events (more than 5).
> [ECO-1752] fix mock data

- src/rust/Cargo.lock
- src/rust/allowlister3000/Cargo.toml
- src/rust/allowlister3000/README.md
- src/rust/allowlister3000/src/main.rs
This PR makes it so that you can change the allowlister3000's allowlist with 0% downtime.
Start the allowlister3000 and follow the README instructions to reload the allowlist.
> [ECO-1778] make allowlister3000 hot-reloadable

- src/typescript/frontend/tailwind.config.js
> [ECO-1835] Fix slider animation

- src/typescript/frontend/src/components/text-carousel/TextCarousel.tsx
Fix the text on the carousel so it repeats correctly aka 1, 2, 3, 1, 2, 3, 1, 2, 3 instead of 1, 1, 1, 2, 2, 2, 3, 3, 3.
Ocular patdown
> [ECO-1845] Fix carousel text to flatten correctly

- src/typescript/README.md
- src/typescript/frontend/vercel-submodule.sh
Update steps for using fine-grained token access to clone submodule during Vercel build.
Deployment build
> [ECO-1888] Add fine-grained token submodule fix

- src/typescript/frontend/src/components/pages/home/components/animation-config.ts
- src/typescript/frontend/src/components/pages/home/components/table-card/TableCard.tsx
> [ECO-1885] Update live event colors to new color schema

- cfg/cspell-dictionary.txt
- src/rust/allowlister3000/README.md
- src/rust/allowlister3000/add.sh
- src/rust/allowlister3000/remove.sh
This PR adds two scripts:
- `add.sh`: adds an address to the allowlister list.
- `remove.sh`: removes an address from the allowlister list, and creates a backup of the old list.
Run the `add.sh` and `remove.sh` scripts against a random text file.
> [ECO-1926] add add and remove scripts for allowlister

- src/typescript/frontend/next.config.mjs
The default behavior of nextjs's  client-side Router Cache is unfortunately opaque and problematic, since it is an opt-out caching behavior that is independent of the caching mechanisms/configurations you can set for server requests, and it affects all data flowing through a client. Note that it is on a per-client basis- meaning the client's browser data supersedes the server cache.
That is, if you're a user visiting an emojicoin's market page and you make 5 trades and refresh the page- you won't see those 5 trades for at least 30 seconds because of the opt-out client-side router cache. But if a new user visits the page in the next 2 seconds after you make those trades, they will see the right data, but only because they're on an entirely separate client. This is why hard refresh tends to …
> [ECO-1956] Attempt to fix nextjs caching issues

- src/typescript/frontend/src/components/pages/emojicoin/components/chat/ChatBox.tsx
- src/typescript/frontend/src/components/pages/emojicoin/components/trade-history/index.tsx
- src/typescript/frontend/src/lib/store/event-utils.ts
- src/typescript/frontend/src/lib/utils/sort-events.ts
Every once in a while the component display gets out of sync and it appears the data is delayed but it's actually just at the bottom of the component. I believe this is due to the way the server component (React Server Component, aka RSC) data is merged with the state data. Initially it's RSC payload => state data later.
But if you refresh the page, I believe it's existing state data => RSC payload, which contradicts the normal assumptions I made when displaying this data.
To ensure there are no issues with data presentation, I've added a useMemo function to merge, deduplicate, and sort the swap and chat data from the server and from state.
While this won't ensure we never see stale data, which we will fully address later, it eliminates a possible source of incorrect data presentation. …
> [ECO-1958] Add `useMemo` to sort, deduplicate, and merge chat/swap events that are in state and the server

- src/typescript/frontend/src/components/emoji-picker/ColoredBytesIndicator.tsx
- src/typescript/frontend/src/components/error-boundary/styles.css
- src/typescript/frontend/src/components/header/components/mobile-menu-item/index.tsx
- src/typescript/frontend/src/components/header/components/mobile-menu-item/types.ts
- src/typescript/frontend/src/components/header/components/mobile-menu/animations.ts
- src/typescript/frontend/src/components/header/components/mobile-menu/components/animated-dropdown-item/index.tsx
- src/typescript/frontend/src/components/header/components/mobile-menu/index.tsx
- src/typescript/frontend/src/components/header/components/mobile-menu/styled.tsx
- src/typescript/frontend/src/components/header/components/mobile-menu/types.ts
- src/typescript/frontend/src/components/header/index.tsx
- src/typescript/frontend/src/components/header/styled.tsx
- src/typescript/frontend/src/components/header/wallet-button/ConnectWalletButton.tsx
- src/typescript/frontend/src/components/link/const.ts
- src/typescript/frontend/src/components/loader/index.tsx
- src/typescript/frontend/src/components/modal/BaseModal.tsx
- src/typescript/frontend/src/components/pages/launch-emojicoin/ClientLaunchEmojicoinPage.tsx
- src/typescript/frontend/src/components/pages/not-found.tsx
- src/typescript/frontend/src/components/pages/verify/VerifyPage.tsx
- src/typescript/frontend/src/components/svg/icons/RiseIcon.tsx
- src/typescript/frontend/src/components/wallet/WalletDropdownItem.tsx
- src/typescript/frontend/src/components/wallet/WalletDropdownMenu.tsx
- src/typescript/frontend/src/components/wallet/WalletModal.tsx
- src/typescript/frontend/src/context/ContentWrapper.tsx
- src/typescript/frontend/src/context/wallet-context/AptosContextProvider.tsx
- src/typescript/frontend/src/context/wallet-context/WalletModalContext.tsx
> [ECO-1959] Miscellaneous small frontend fixes

- src/typescript/frontend/src/components/pages/emojicoin/components/trade-emojicoin/SwapComponent.tsx
- src/typescript/frontend/src/components/pages/launch-emojicoin/ClientLaunchEmojicoinPage.tsx
- src/typescript/frontend/src/components/pages/pools/ClientPoolsPage.tsx
- src/typescript/frontend/src/components/pages/pools/components/liquidity/index.tsx
- src/typescript/frontend/src/components/pages/pools/components/pools-table/index.tsx
Use query params to predefine inputs.
- `buy=AMOUNT` to buy a certain amount.
- `sell=AMOUNT` to sell a certain amount.
- `add=AMOUNT` to add a certain amount of liquidity.
- `remove=AMOUNT` to remove a certain amount of liquidity.
- `pool=EMOJIS` to preselect a pool.
- `emojis=EMOJIS` to predefine the value of the single input of the page.
> [ECO-1710] use query params to predefine inputs

- src/typescript/frontend/src/components/pages/emojicoin/components/trade-history/table-row/index.tsx
- src/typescript/frontend/src/components/pages/emojicoin/components/trade-history/trade-history.css
The borders for trade history row entries was removed in a previous PR but shouldn't have been.
Visual
> [ECO-1983] Fix borders for trade history entries

- src/typescript/frontend/src/components/pages/emojicoin/components/chat/ChatBox.tsx
- src/typescript/frontend/src/components/pages/emojicoin/components/trade-history/index.tsx
- src/typescript/frontend/src/lib/store/event-store.ts
- src/typescript/frontend/src/lib/store/event-utils.ts
- src/typescript/frontend/src/lib/utils/sort-events.ts
- src/typescript/sdk/src/emoji_data/utils.ts
- src/typescript/sdk/src/types/types.ts
This PR stores the latest trades in `localStorage` to avoid not seeing your
trades when refreshing really quick after a trade.
Trade A will be deleted from `localStorage` after a trade B that happens 60
seconds after trade A. This ensures every trade is saved for at least 60
seconds, which should always be enough for inbox to catch up.
Make a trade and refresh as fast as possible. The trade should appear in trade
history.
Check the `Application` tab in your browser dev tools and check that there is a
field named `swaps` in your `localStorage` after making a trade.
> [ECO-1950] Add local caching for trade and swap history

- src/typescript/frontend/src/middleware.ts
- src/typescript/frontend/src/utils/pathname-helpers.ts
- The middleware.ts resolves names by joining them with a comma even though the standard is using a ; semicolon.
- This PR aims to fix it and consolidate the logic to a single place.
Test registering a market and test viewing markets that already exist with multiple emojis.
> [ECO-1991] Fix emoji name resolution in `middleware.ts`

- doc/doc-site/docs/about/how-it-works.md
- src/typescript/frontend/src/components/pages/pools/components/liquidity/index.tsx
- src/typescript/frontend/src/utils/parse-changes-for-balances.ts
> [ECO-2000] Fix liquidity pool issues

- src/typescript/frontend/src/app/home/page.tsx
- src/typescript/frontend/src/app/layout.tsx
- src/typescript/frontend/src/app/market/[market]/page.tsx
- src/typescript/frontend/src/app/market/api/route.ts
- src/typescript/frontend/src/app/page.tsx
- src/typescript/frontend/src/components/charts/ChartContainer.tsx
- src/typescript/frontend/src/lib/queries/sorting/market-data.ts
- src/typescript/frontend/src/lib/queries/sorting/query-params.ts
- src/typescript/frontend/src/lib/queries/sorting/types.ts
- src/typescript/frontend/src/lib/routes/home-page-params.ts
- src/typescript/frontend/src/lib/store/server-to-client/FetchFromServer.tsx
- src/typescript/frontend/src/lib/store/server-to-client/StoreOnClient.tsx
- src/typescript/frontend/src/lib/utils/prettify-hex.ts
As @CRBl69 pointed out, the aggregate-market queries are nearly entirely unnecessary and cause the page to load a lot slower.
We can remove these from the homepage and use existing data to populate the frontend with data for the main page
The only case where we would need to add new data is by replacing the Chart search function. Right now we use the data in state to search for markets, but we can use an asynchronous server action or a `GET` call with a `[markets]/api.ts` to call this.
For now, to keep things simple, I removed the aggregate markets query from the home page and call it when the Chart loads. We can still remove it entirely but it would mean replacing the Chart search logic and behavior.
Check the logs on vercel to see if the function is called when the home page is loaded. …
> [ECO-2059] Remove aggregate-market queries from the home page

- src/typescript/frontend/src/components/pages/home/components/table-card/LinkOrAnimationTrigger.tsx
- src/typescript/frontend/src/components/pages/home/test-generate-event/event-generator.ts
- src/typescript/sdk/src/emoji_data/types.ts
- src/typescript/sdk/src/emoji_data/utils.ts
- src/typescript/sdk/src/markets/utils.ts
- src/typescript/sdk/src/types/json-types.ts
- src/typescript/sdk/src/types/types.ts
- src/typescript/sdk/tests/unit/emoji-regex.test.ts
Visual testing + using it an incredible amount to test things visually.
> [ECO-2061] Add test event generator for the frontend

- src/typescript/frontend/src/components/header/index.tsx
- src/typescript/frontend/src/components/pages/home/components/emoji-table/AnimatedClientGrid.tsx
- src/typescript/frontend/src/components/pages/home/components/emoji-table/ClientGrid.tsx
- src/typescript/frontend/src/components/pages/home/components/emoji-table/utils.ts
> Fix the left grid line not showing up when searching for an emoji; clear search input on navigation to home page

- .github/workflows/production-branch-protection.yaml
- src/rust/example.env
When trying to merge into `production` from `ECO-2116`:
> [ECO-2116] Add a branch protection rule to only allow merging to `production` from `main`

- src/cloud-formation/deploy-dev.yaml
Kill the `dev` stack due to CIDR conflicts on subnet rename/replace operation
TBD
> [ECO-2141] Declaratively kill stack

- src/rust/broker/src/main.rs
- src/rust/broker/src/processor_connection.rs
- src/rust/broker/src/server.rs
- src/rust/broker/src/util.rs
This PR adds retry functionality for the broker.
A connection is considered successful when a network connection was established and the network connection lasted for at least 10 seconds.
- When starting the broker, if a successful connection cannot be established, exit.
- When a connection breaks, the broker will try to reconnect 10 times.
- When a connection breaks, retry instantly (after 1 second).
- When a retry fails, retry after 15 seconds.
- When no retries are left, exit.
- When a retry results in a successful connection, reset the number of retries left.
1. Export `RUST_LOG=broker=trace` to get as much info as possible.
1. Start the broker by itself, assert that it does not try to reconnect.
1. Start the processor with docker compose.
1. Start the broker, it should connect.
1. …
> [ECO-2142] Implement retry functionality for the broker

- src/typescript/frontend/src/components/pages/home/components/emoji-table/AnimatedClientGrid.tsx
- src/typescript/frontend/src/components/pages/home/components/emoji-table/ClientGrid.tsx
- src/typescript/frontend/src/components/pages/home/components/emoji-table/utils.ts
The animations got screwed up a bit back when I was fixing the lack of a grid line when search emojis are used.
I added the `index` to each grid item component key, meaning it re-animates any time its position in the grid changes, but that's not what we want, because for bump order in particular, the animations are set up to be triggered by changes to the `orderedGrid` variable, not the component key. (They're set up this way by `framer-motion`, which animates the grid order, indicated by the presence of the `layout` prop in an animated component)
In order to fix this bug while still respecting the original fix, I've added the `searchEmojis` to the component keys and removed the `index` from the component key.
Thus the `searchEmojis` changing will trigger a re-render, which subsequently …
> [ECO-2169] Fix animations by updating the component `keys` for the emoji grid items

- src/docker/compose.local.yaml
- src/docker/deployer/sh/entrypoint.sh
The `deployer` image for local e2e/ci tests does not need to wait for all services to be ready. It can merely wait for the `localnet` service to be started, and then check to make sure the REST API and the faucet API are ready.
Ran a lot of manual tests with bash. Will be running it all day, too.
> [ECO-2178] Speed up the startup time of the `deployer` image

- src/typescript/frontend/src/lib/utils/allowlist.ts
I noticed since the Galxe campaign may be inactive/unused fairly soon, we can re-order the fetch calls to make the `verify` process a bit faster, since right now it can take about 3-4 seconds.
> [ECO-2184] Re-order `allowlist` fetch checks to check `allowlister3000` first

- src/typescript/frontend/src/components/pages/verify/VerifyPage.tsx
> [ECO-2191] Remove `Join Here` from the access denied message

- src/typescript/frontend/src/components/header/components/mobile-menu/index.tsx
- src/typescript/frontend/src/components/header/constants.ts
- src/typescript/frontend/src/router/routes.ts
This PR updates the "START HERE" button to say "DOCS".
It also fixes an old bug that made it so that the moblie menu version of the "START HERE" button did not open in a new tab. Now it does.
See Vercel.
> [ECO-2215] Update "Start here" button to "Docs" and fix mobile menu button not launching in new tab

- src/typescript/frontend/src/components/pages/emojicoin/components/trade-emojicoin/SwapComponent.tsx
This PR adds a:
- sell 100% of your emojicoins buttom
- buy emojicoins using 50% of your APT balance button
- buy emojicoins using 100% of your APT balance button
on the market page of an emoji.
See vercel.
> [ECO-2016] Add new sell/buy 50%/100% buttons

- src/typescript/frontend/src/components/inputs/search-bar.tsx
- src/typescript/frontend/src/components/pages/pools/styled.tsx
This PR removes 1px to the width of the border of the search bar and fixes the left padding of the search bar on the pools page.
See vercel.
> [ECO-2203] Match search bar with figma design

- src/typescript/frontend/src/components/pages/emoji-picker/EmojiPicker.tsx
This PR fixes the emoji picker not rendering correctly in browers where light mode is set as default.
It also fixes a long lasting bug that simply prints errors in the console. This was due to the `drag` property being applied to the `div` when decontructing `props` (`{...props}`).
See Vercel.
> [ECO-2211] Fix emoji picker not deplaying correctly for users with light mode as default

- src/typescript/sdk/src/indexer-v2/queries/client.ts
This PR fixes a small error with the header being sent to PostgREST (`-` being used instead of `/`).
> [ECO-2224] Fix wrong separation character being used in header

- src/typescript/frontend/src/lib/server-env.ts
The check removed made sure that the indexer isn't running on localhost when
the network is set on testnet. This makes it impossible to test something with
a local indexer against testnet. Since this is a workflow that is very used,
and the check does not seem to be very important, it is removed.
> [ECO-2225] Remove check that renders local indexer testing with testnet impossible

- src/docker/README.md
- src/docker/localnet/Dockerfile
- src/docker/localnet/check-if-stale.sh
- src/docker/utils/prune.sh
- src/typescript/pnpm-lock.yaml
- src/typescript/sdk/package.json
- src/typescript/sdk/tests/utils/publish.ts
Delete this sentence and provide a description of how to test the changes in
this PR.
> [ECO-2222] Clean up the localnet setup process

- src/typescript/frontend/src/components/emoji-picker/EmojiPickerWithInput.tsx
- src/typescript/frontend/src/components/pages/emojicoin/components/chat/components/message-container/index.tsx
Before: <img width="337" alt="image" src="https://github.com/user-attachments/assets/e316449d-3609-45d4-a5fc-8748e613254f">
After: <img width="332" alt="image" src="https://github.com/user-attachments/assets/dd3c39cc-7d96-4695-9497-1164670b121e">
The chat box input looks a little off without a preview, since it's just at the bottom with no grid lines or anything. I've added a very transparent preview of the input box if the user's wallet isn't connected.
Check the preview, plus manual testing!
> [ECO-2227] Add chat box input preview if wallet isn't connected

- src/typescript/frontend/src/components/pages/launch-emojicoin/hooks/use-is-market-registered.ts
- src/typescript/frontend/src/components/pages/launch-emojicoin/hooks/use-register-market.ts
- src/typescript/frontend/src/components/pages/launch-emojicoin/memoized-launch/components/launch-or-goto.tsx
- src/typescript/frontend/src/components/pages/launch-emojicoin/memoized-launch/index.tsx
Change the launch emojicoin button to say:
Manual testing.
> [ECO-2209] Make insufficient balance for market registration clearer

- src/typescript/frontend/src/components/pages/emojicoin/ClientEmojicoinPage.tsx
- src/typescript/frontend/src/components/pages/emojicoin/components/trade-history/index.tsx
- src/typescript/frontend/src/components/pages/home/components/emoji-table/AnimatedClientGrid.tsx
- src/typescript/frontend/src/context/ConnectToWebSockets.tsx
- src/typescript/frontend/src/context/event-store-context/StateStoreContextProviders.tsx
- src/typescript/frontend/src/context/event-store-context/hooks.tsx
- src/typescript/frontend/src/hooks/use-reliable-subscribe.ts
- src/typescript/frontend/src/lib/store/event/event-store.ts
- src/typescript/frontend/src/lib/store/event/local-storage.ts
- src/typescript/frontend/src/lib/store/event/types.ts
- src/typescript/frontend/src/lib/store/event/utils.ts
- src/typescript/frontend/src/lib/store/server-to-client/StoreOnClient.tsx
- src/typescript/frontend/src/lib/store/websocket/store.ts
- src/typescript/frontend/src/utils/index.ts
- src/typescript/package.json
- src/typescript/sdk/src/broker-v2/client.ts
- src/typescript/sdk/src/utils/misc.ts
- src/typescript/sdk/tests/unit/filter-extract.test.ts
- src/typescript/turbo.json
Manual testing, although some simple unit tests were added for function logic.
Ideally we'd add unit tests for this, but for now we just want to get it working. It's possibly within the scope of this PR to add unit tests for this- it would definitely be nice to have.
> [ECO-2229] Fix the websocket client incoming event logic by using proper `immer` functionality

- src/typescript/frontend/package.json
- src/typescript/frontend/src/components/pages/verify/session-info.ts
- src/typescript/frontend/src/components/pages/verify/verify.ts
- src/typescript/frontend/src/context/providers.tsx
- src/typescript/frontend/src/lib/server-env.ts
- src/typescript/package.json
- src/typescript/pnpm-lock.yaml
- src/typescript/sdk/package.json
- src/typescript/sdk/src/emojicoin_dot_fun/emojicoin-dot-fun.ts
Register a market  with the preview deployment and see if the transaction succeeds!
> [ECO-2241] Attempt to fix wallet adapter issues with a version bump and config update

- src/typescript/frontend/src/components/pages/emojicoin/ClientEmojicoinPage.tsx
- src/typescript/frontend/src/components/pages/emojicoin/components/trade-emojicoin/LiquidityButton.tsx
- src/typescript/frontend/src/components/pages/emojicoin/components/trade-emojicoin/SwapButton.tsx
- src/typescript/frontend/src/components/pages/emojicoin/components/trade-emojicoin/SwapComponent.tsx
- src/typescript/frontend/src/context/providers.tsx
- src/typescript/frontend/src/lib/hooks/queries/use-grace-period.ts
This PR integrates the new grace period dynamics:
- When the market is in a grace period:
- the *BONDING CURVE: XY%* is replaced with *GRACE PERIOD (X MINUTES AND Y SECONDS LEFT)*
- if the current user is not the market registrant:
- the swap button is disabled
- the swap button has an on hover popup that explains why it is disabled
In order to prevent the market registrant to trade on his own market, in case
of query failure, the UI will let anyone try to trade.
On trade, the grace period is automatically updated !
Go to vercel, register a market, go on the market page with two different accounts (registrant and another one).
> [ECO-2161] Update market page with new grace period dynamics

- src/typescript/frontend/src/lib/store/event/event-store.ts
- src/typescript/frontend/src/lib/store/event/local-storage.ts
It's breaking production because it's trying to read from local storage, since there's values there. 
Removing the initial state to essentially reset it very quickly
It has to be merged into production to see if it truly fixes it, but all tests should pass.
> [ECO-2257] Patch event store to not pull from local storage because it's currently cached

- src/typescript/frontend/src/lib/server-env.ts
- src/typescript/frontend/src/lib/store/event/utils.ts
- src/typescript/sdk/src/indexer-v2/queries/client.ts
- src/typescript/sdk/src/server/env.ts
- src/typescript/sdk/tests/e2e/queries/testnet/simple.test.ts
- src/typescript/sdk/tests/e2e/schema.test.ts
The chart is currently not dividing the time returned by a function that takes in a bigint of microseconds, so it thinks it's nearly the year 50,000.
During the big update for indexer v2, the `server-env.ts` file lost its `import "server-only"` directive at the top of the file. Currently it can be accidentally imported to client files. I've also fixed that
I'll add unit tests for some of this logic later, but for now we just have to visually ensure it's correct. It's extremely obviously wrong at the moment, so just check that the latest bar on the chart is `'24` and not the year 50447 (will display as `'47`) and that means it's working correctly.
> [ECO-2286] Fix the incorrect chart bar times

- src/move/rewards/Move.toml
- src/move/rewards/sources/emojicoin_dot_fun_rewards.move
1. Remove an erroneous shift when multiplying a `Q64` by a scalar.
1. Add clarifying comment about rewards probability per octa of fees paid.
1. Bump patch version.
Published on testnet for further integration testing.
> [ECO-2307] Fix rewards probability calculations 

- src/typescript/frontend/tests/e2e/global.setup.ts
- src/typescript/sdk/src/utils/test/docker/docker-test-harness.ts
Change it in both places, in playwright config setTimeout and in the `docker-test-harness.ts` file as well.
Tests will run in CI.
> [ECO-2311] Increase the max wait time for the frontend container being healthy and for the playwright setup timeout

- src/typescript/example.env
- src/typescript/frontend/src/components/geoblocking/index.tsx
This PR adds a little bit of height to the geoblocking banner so that it can completly hide the price feed
> [ECO-2333] Fix VPN banner styling

- src/typescript/frontend/src/components/pages/home/components/main-card/MainCard.tsx
This PR aims to replace the confusing `00` on the home page.
Here are some options:
Personal opinion: this one feels the most confusing to me. It seems like it's the market name to me.
Personal opition: not a fan of the emoji, but this is the best compromise between having and emoji and clarity.
Personal opinion: maybe a bit too much.
Personal opition: just like option A1, but "featured" might give the false idea that the market is somehow officially endorsed.
Personal opinion: I like the look, very clean, but not very visible.
Personal opinion: sometimes, you don't need a reason to hate something.
Personal opinion: Looks the cleanest out of them all, but has the endorsement issue.
> [ECO-2280] Replace 00 on home page

- src/typescript/frontend/src/components/inputs/input-numeric/index.tsx
- src/typescript/frontend/src/components/pages/emojicoin/components/trade-emojicoin/SwapComponent.tsx
- src/typescript/frontend/src/components/pages/pools/components/liquidity/index.tsx
- src/typescript/frontend/src/lib/utils/decimals.ts
- src/typescript/frontend/tests/e2e/market-order.spec.ts
- src/typescript/frontend/tests/e2e/search.spec.ts
- src/typescript/sdk/src/utils/index.ts
- src/typescript/sdk/src/utils/validation.ts
- src/typescript/sdk/tests/unit/validation.test.ts
This PR fixes input fields on the market and the pools pages.
Before, inputing small values would glitch the inputs.
Now, you can input values as small as 0.00000001, which is the smallest number you can trade.
Input small values on the market and the pools pages in vercel.
> [ECO-2313] Fix input fields on market and pools pages

- src/typescript/frontend/src/app/verify_status/page.tsx
- src/typescript/frontend/src/components/pages/verify_status/VerifyStatusPage.tsx
- src/typescript/frontend/src/components/pages/verify_status/get-verification-status.ts
- src/typescript/frontend/src/lib/utils/allowlist.ts
- src/typescript/frontend/src/middleware.ts
To easily test the verification status of individual allowlists (galxe campaign, allowlister3000, geoblocked), we need a custom page that displays the value of all three depending on the wallet account address and user's IP address.
Example:
Manual testing.
> [ECO-2361] Add test page `/verify_status` for checking Galxe campaign, allowlisted, and geoblocked status

- src/typescript/frontend/src/components/charts/PrivateChart.tsx
- src/typescript/frontend/src/components/pages/emoji-picker/EmojiPicker.tsx
This PR fixes a couple of frontend errors that appeared in the console and made it very annoying to actually read anything there:
- `Chart` (which is a client component) was `async`, now it's not.
- `filterEmojis` was accidentally passed to a `div` when it shouldn't have been, now it's not.
See vercel, open console.
> [ECO-2369] Remove frontend console errors

- src/typescript/frontend/src/components/charts/PrivateChart.tsx
- src/typescript/frontend/src/lib/chart-utils/index.ts
- src/typescript/frontend/src/lib/store/event/candlestick-bars.ts
- src/typescript/frontend/src/lib/store/event/event-store.ts
OLD:
NEW:
Lots of visual and manual testing.
> [ECO-2372] Fix candlestick chart issues

- src/typescript/frontend/src/components/pages/emojicoin/components/chat/components/message-container/index.tsx
This PR fixes emoji chat messages that did not break and overflowed the chat box.
See `/market/infinity;TOP_arrow` chat history on vercel.
> [ECO-2382] Fix non-breaking chat messages

- src/typescript/frontend/src/app/global.css
- src/typescript/frontend/src/components/pages/home/components/table-card/TableCard.tsx
- src/typescript/frontend/src/components/pages/pools/components/pools-table/components/table-header/index.tsx
- src/typescript/frontend/src/components/selects/dropdown-menu/index.tsx
- src/typescript/frontend/src/components/selects/dropdown-menu/module.css
- src/typescript/frontend/src/components/table/index.tsx
- src/typescript/frontend/src/components/text/index.tsx
- src/typescript/frontend/src/components/text/theme.ts
- src/typescript/frontend/src/components/text/types.ts
- src/typescript/frontend/tailwind.config.js
This PR fixes a bug where a line would break on the home page if a market had three emojis in its symbol.
This PR also adds the possibility to use `className` with the `Text` component and makes the `Text` component code more clear.
See vercel (currently there is such a market on page 3 but this might change when you review).
> [ECO-2256] Fix line break on market with three emojis

- src/docker/compose.yaml
This PR adds useful logging variables to PostgREST.
- Timing is now returned in header.
- You can pass `Accept: application/vnd.pgrst.plan` to get the query plan, to check index usage.
- You can pass an `X-Request-Id` header to trace requests.
- All requests are logged.
Run docker compose.
> [ECO-2379] Add log environment variables for PostgREST

- src/typescript/sdk/src/client/emojicoin-client.ts
- src/typescript/sdk/src/utils/test/calculate-periodic-boundaries-crossed.ts
- src/typescript/sdk/src/utils/test/index.ts
- src/typescript/sdk/tests/e2e/queries/client/submit.test.ts
- src/typescript/sdk/tests/unit/period-boundaries.test.ts
- src/typescript/turbo.json
The `submit.test.ts` e2e test for the SDK would sometimes fail because it wasn't properly calculating the number of period boundaries crossed between two bump events.
To fix it, I added a function that calculates the number of period boundaries crossed between a start time and end time and calculate the number of period boundaries crossed between any two bump event start/end times.
The tests will run in CI for this PR.
> [ECO-2390] Fix flaky sdk e2e test due to period boundary cross miscalculation

- src/docker/frontend/Dockerfile
- src/typescript/frontend/next.config.mjs
- src/typescript/frontend/package.json
- src/typescript/package.json
- src/typescript/sdk/package.json
- src/typescript/turbo.json
Have the docker container, when built, ignore linting/typescript type errors so that playwright doesn't show up as failing when it's merely a linting/type issue
This is okay because we check this in CI in other actions anyway, and we rebuild the frontend container in all tests.
Tested locally with another PR that's currently failing linting/type checks.
> [ECO-2391] Ignore lint/type errors when building the frontend Docker container

- src/typescript/frontend/src/components/pages/home/components/emoji-table/ClientGrid.tsx
- src/typescript/frontend/src/components/pages/home/components/emoji-table/utils.ts
This PR fixes a bug where the home page grid would double render when searching for something.
Search, check no double animation.
> [ECO-2364] Fix double rendering issue on home page

- README.md
> [ECO-2415] Add `cherry-pick` strategy to the `README.md`

- .github/workflows/push-broker.yaml
Parallelize broker image builds using a GitHub actions matrix strategy, bump processor version
`broker-v0.9.2` tag build completed
> [ECO-2403] Parallelize docker image builds

- src/cloud-formation/deploy-indexer-main.yaml
- src/cloud-formation/deploy-indexer-production.yaml
1. Bump image bersions for broker and processor to `v1.0.0`, which are located on `main` and `emojicoin-dot-fun` branches of the respective repos
SDK tests are passing for v1.0.0 AMD builds on other PRs
> [ECO-2419] Bump stack image versions

- src/move/rewards/sources/emojicoin_dot_fun_claim_link.move
1. Implement `add_public_keys_and_fund_gas_escrows` API with 100% coverage testing.
1. Update vector-wise `for_each` to `for_each_ref` since the latter does not have to reverse the vector in place before iteration.
1. Split public keys into `claimed` and `eligible` tables for ease of fetching eligible public keys.
1. Update assorted APIs as needed for `claimed` and `eligible` table paradigm.
`emojicoin_dot_fun_claim_link` module tested to 100% coverage. From in repo root:
```sh
cd src/move/rewards
```
```sh
aptos move test --dev --move-2 --coverage
```
Note that per https://github.com/aptos-labs/aptos-core/issues/15284 the `test_general_flow` test fails non-deterministically. If it fails, running it again will probably result in a pass, eventually.
> [ECO-2420] Refactor claim link module for ease of DevOps

- src/docker/deployer/Dockerfile
- src/docker/deployer/sh/build-publish-payloads.sh
- src/docker/deployer/sh/init-profile.sh
e2e tests will use it when it's done deploying and we'll know if it fails/succeeds or not for sure by then.
> [ECO-2430] Build `deployer` service with Aptos CLI `v4.4.0`

- src/move/rewards/README.md
Add `--move-2` flag to CLI command now that package has Move 2 syntax.
Publishing on devnet
> [ECO-23439] Add `--move-2` flag to rewards publish command

- src/move/rewards/sources/emojicoin_dot_fun_claim_link.move
Update default claim amount to 5 APT
`aptos move test --dev --move-2` passes, except for the non-deterministic `test_general_flow` documented in #360 and https://github.com/aptos-labs/aptos-core/issues/15284
> [ECO-2442] Update default claim amount

- README.md
- doc/doc-site/docs/resources/audit.md
Update audited git tag references in README and in docs site
Local markdown render clickthrough
> [ECO-2448] Update audited git tag references

- src/typescript/frontend/src/app/market/[market]/page.tsx
- src/typescript/frontend/src/lib/queries/aptos-client/market-view.ts
We didn't properly serialize the data for `unstable_cache` so the build was failing at preview time. Now we serialize by typing the data, stringifying it, and then parsing it later when pulling from the cache or from a fetch.
Testing in the preview build again.
> [ECO-2456] Add serialization fix for cached query

- src/cloud-formation/indexer.cfn.yaml
Merge #389 changes into `production`
Deployment on testnet stack
> [ECO-2461] Merge indexer resource increases from `main` to `production`

- src/typescript/frontend/src/context/providers.tsx
Reconnecting manually is cumbersome and this should have been flipped back on a while ago anyway
Testing in preview build
> [ECO-2467] Add back in autoConnect for the wallet adapter

- src/typescript/frontend/src/context/providers.tsx
Reconnecting manually is cumbersome and this should have been flipped back on a while ago anyway
Testing in preview build
> [ECO-2467] Merge `main` to `production`, add back in autoConnect for the wallet adapter

- .gitignore
- src/typescript/frontend/src/middleware.ts
Fairly self explanatory- the image won't load unless the matcher allows it through on `middleware.ts` unauthenticated (that is, let an unauthenticated user see the okx logo in the wallet adapter).
We didn't have to do this before because the wallet adapter used all SVGs and those aren't public/static files, but pure HTML elements.
> [ECO-2470] Add okx icon/logo to middleware.ts so it shows up in the wallet adapter on `/verify`

- src/typescript/frontend/src/lib/hooks/queries/use-wallet-balance.ts
- src/typescript/sdk/src/emojicoin_dot_fun/aptos-framework.ts
- src/typescript/sdk/src/emojicoin_dot_fun/index.ts
The external indexer API (the Aptos Labs hosted one) expects addresses *without* leading zeroes. If you send a CoinType with a leading zero in the first third of the MoveStruct (e.g. `0x0...beef::coin_module::CoinType`, even if the address is correct, the `current_fungible_asset_balance` query will return zero.
One out of 16 addresses will start with a 0, so this was a fairly pervasive issue.
An example is the two billiard coin:
https://explorer.aptoslabs.com/coin/0x072a70c925a8260880de81b500ecd743e652cd74797eb1d024f44ea195cbf8bb::coin_factory::Emojicoin?network=mainnet
Note the address starts with 0x072
The issue is that AIP-40 stipulates that a standardized address *does* include leading zeros, but the indexer expects no leading zeroes.
We could parse it and conform to the expected …
> [ECO-2488] Fix emojicoin balance query by using the view function instead of the external indexer API

- src/typescript/frontend/src/components/pages/home/components/emoji-table/utils.ts
- src/typescript/frontend/src/components/pages/home/components/table-card/TableCard.tsx
> [ECO-2487] Fix 24h volume, update text to say recent volume when on bump order

- src/cloud-formation/README.md
- src/cloud-formation/deploy-indexer-production.yaml
- src/cloud-formation/indexer.cfn.yaml
- src/typescript/frontend/src/components/emoji-picker/EmojiPickerWithInput.tsx
- src/typescript/frontend/src/components/pages/emojicoin/components/mobile-grid/index.tsx
- src/typescript/frontend/src/configs/index.ts
- src/typescript/frontend/src/configs/local-storage-keys.ts
- src/typescript/frontend/src/context/language-context/helpers.ts
- src/typescript/frontend/src/context/theme-context/index.tsx
- src/typescript/frontend/src/hooks/use-is-user-geoblocked.ts
- src/typescript/frontend/src/utils/index.ts
Merge recent assorted changes
See git diff against `main`
> [ECO-2503] Merge assorted recent changes to production

- src/cloud-formation/deploy-indexer-fallback.yaml
- src/cloud-formation/deploy-indexer-main.yaml
- src/cloud-formation/deploy-indexer-production.yaml
Bump deploy files to use the processor (and broker) with updates to the `price_feed` where it returns `market_state` as well.
Unit/e2e tests, testing on the `main` deployment branch. Currently `main` is pointing to the old stack and thus is "broken" (price feed isn't working).
Once these changes take effect, the `main` preview build should function perfectly.
> [ECO-2499] Update deploy files

- src/typescript/frontend/src/configs/local-storage-keys.ts
Move JSON deserialization into try catch to avoid failure.
> [ECO-2516] Prevent JSON deserialization issue

- src/typescript/frontend/src/configs/local-storage-keys.ts
Merge local storage hotfix to production. No try/catch around the parse means old invalid JSON values aren't correctly caught.
This fixes that.
Tested by manually setting `@econia-labs/emojicoin-frontend_theme` local storage value to `light`.
> [ECO-2516] Merge local storage JSON parse hotfix to production

- src/typescript/frontend/package.json
- src/typescript/frontend/src/components/svg/icons/NightlyIcon.tsx
- src/typescript/frontend/src/context/wallet-context/WalletItem.tsx
- src/typescript/pnpm-lock.yaml
Test with the adapter on testnet if possible, otherwise let testers test on the `main` build, since we can't test on `mainnet`.
> [ECO-2515] Add Nightly wallet back to the adapter, update wallet adapter to include Apple OAuth

- src/typescript/frontend/src/lib/queries/sorting/query-params.ts
This PR fixes a bug that made it impossible to sort by market cap.
The issue was due to how query parameters for the home page were handled.
The fix should prevent this from happening in the future, even if we change the default sorting order again.
> [ECO-2526] Fix bug where you can't sort by market cap

- src/typescript/frontend/src/components/EmojiPill.tsx
- src/typescript/frontend/src/components/header/wallet-button/ConnectWalletButton.tsx
- src/typescript/frontend/src/components/pages/emojicoin/components/trade-history/table-row/index.tsx
- src/typescript/frontend/src/components/pages/pools/components/liquidity/index.tsx
- src/typescript/frontend/src/components/pages/pools/components/pools-table/components/table-header/index.tsx
- src/typescript/frontend/src/components/pages/pools/components/pools-table/components/table-row-desktop/XprPopup.tsx
- src/typescript/frontend/src/components/pages/pools/components/pools-table/components/table-row-desktop/index.tsx
- src/typescript/frontend/src/components/popup/index.tsx
This PR adds a button to go to the market page from the pools page.
This also optimizes the pools page by using `Number` instead of `Big` for the XPR calculations. This looses some precision but is not that visible.
It also refactors the `Popup` component with default styling.
> [ECO-2266] Add go to page button

- src/typescript/frontend/src/lib/utils/get-user-rank.ts
This PR update the rank logic to use pre-sawp balance on sell and post-swap balance on buy.
See the trading history on a market page.
> [ECO-2473] Use balance before swap to display rank emoji

- cfg/cspell-frontend-dictionary.txt
- src/typescript/frontend/src/components/FormattedNumber.tsx
- src/typescript/frontend/src/components/pages/emojicoin/components/main-info/BondingProgress.tsx
- src/typescript/frontend/src/components/pages/emojicoin/components/main-info/MainInfo.tsx
- src/typescript/frontend/src/components/pages/emojicoin/components/trade-emojicoin/SwapComponent.tsx
- src/typescript/frontend/src/components/pages/emojicoin/components/trade-history/index.tsx
- src/typescript/frontend/src/components/pages/emojicoin/components/trade-history/table-row/index.tsx
- src/typescript/frontend/src/components/pages/emojicoin/components/trade-history/table-row/types.ts
- src/typescript/frontend/src/components/pages/home/components/emoji-table/utils.ts
- src/typescript/frontend/src/components/pages/home/components/main-card/MainCard.tsx
- src/typescript/frontend/src/components/pages/home/components/table-card/TableCard.tsx
- src/typescript/frontend/src/components/pages/home/components/table-card/types.ts
- src/typescript/frontend/src/components/pages/pools/components/liquidity/index.tsx
- src/typescript/frontend/src/components/pages/pools/components/pools-table/components/table-row-desktop/XprPopup.tsx
- src/typescript/frontend/src/components/pages/pools/components/pools-table/components/table-row-desktop/index.tsx
- src/typescript/frontend/src/components/price-feed/inner.tsx
- src/typescript/frontend/src/lib/utils/decimals.ts
This PR wraps displayed number in a parameterizable component.
Check all number displays on vercel.
> [ECO-2482] Use number wrapper to display numbers

- src/typescript/frontend/src/components/pages/emojicoin/components/trade-emojicoin/SwapComponent.tsx
We can make the swap component perfectly simulate + not lose precision when displaying input/output amounts and swapping back and forth between buy/sell now.
This is a very small fix.
Already tested locally.
> [ECO-2548] Fix swap component inputs so it swaps the input/output amounts upon buy => sell and vice versa

- src/typescript/frontend/src/components/pages/home/components/table-card/TableCard.tsx
Display a market's all time volume as the secondary metric in the table card when it's the `sortBy` type.
Manual testing + on preview build! Change the sort order in the grid.
> [ECO-2459] Display all time volume as the secondary metric in the table card when it's the `sortBy` type

- src/typescript/frontend/src/lib/store/event/candlestick-bars.ts
- src/typescript/frontend/src/lib/store/event/utils.ts
SSIA, use quote volume instead of base when displaying it in the candlestick bars. This was an oversight when moving from base => quote a few days ago.
Note only the final candlestick bar was incorrect- all of the candlesticks prior to it used quote volume, so it looked like the last bar had an extraordinary amount of volume.
Preview build!
> [ECO-2551] Update volume bars to all use quote volume

- src/typescript/frontend/src/components/header/components/mobile-menu/index.tsx
Right now, if a user is geoblocked, the `Connect Wallet` item in the mobile menu isn't disabled visually, so it's confusing why clicking it doesn't work. The simplest solution for this is just removing it from the mobile menu if the user is geoblocked.
We can't disable the `Menu` item entirely, because that contains the links to the other pages, so we just remove the option to connect the wallet.
Geoblocked:
Not geoblocked:
Tested it locally by clearing my cache and enabling geoblocking, then clearing my cache and disabling geoblocking.
> [ECO-2558] Remove `Connect wallet` in the mobile menu if a user is geoblocked

- src/typescript/frontend/src/components/pages/pools/ClientPoolsPage.tsx
- src/typescript/sdk/src/indexer-v2/queries/index.ts
- src/typescript/sdk/src/indexer-v2/queries/query-params.ts
This PR makes it so that by default, the pool page is sorted by APR.
See pool page on vercel.
> [ECO-2525] Sort pool page by dpr by default

- src/typescript/frontend/src/app/pools/page.tsx
Ocular patdown of the row order on load. Otherwise, this logic is exactly the same as the GET request so it should generally just synchronize the initial load with the first GET request in all different combinations of search params.
> [ECO-2565] Add proper search params to the pools page server component; copy the GET request params logic

- src/typescript/sdk/package.json
> [ECO-2570] Fix package.json linked `tsconfig.*.json` file name for publishing

- src/typescript/sdk/src/markets/utils.ts
- src/typescript/sdk/tests/e2e/calculate-curve-price.test.ts
Dexscreener indicated that we need to calculate price "on top of reserves", not "on top of swap amounts", so we must add a function to calculate the price given the state of reserves after a swap.
> [ECO-2577] Add `calculateCurvePrice` function for dexscreener API

- pnpm-lock.yaml
- src/typescript/frontend/src/app/dexscreener/README.md
- src/typescript/frontend/src/app/dexscreener/asset.ts
- src/typescript/frontend/src/app/dexscreener/events.ts
- src/typescript/frontend/src/app/dexscreener/latest-block.ts
- src/typescript/frontend/src/app/dexscreener/pair.ts
- src/typescript/frontend/src/app/dexscreener/util.test.ts
- src/typescript/frontend/src/app/dexscreener/util.ts
- src/typescript/frontend/src/middleware.ts
- src/typescript/frontend/src/router/routes.ts
- src/typescript/sdk/src/indexer-v2/mini-processor/event-groups/index.ts
- src/typescript/sdk/src/indexer-v2/mini-processor/event-groups/utils.ts
- src/typescript/sdk/src/indexer-v2/queries/app/dexscreener.ts
- src/typescript/sdk/src/indexer-v2/queries/app/index.ts
- src/typescript/sdk/src/indexer-v2/types/index.ts
Continuation of  #422 
Dexscreener API stubs
Dexscreener events cconverion v1
Dexscreener events cconverion v1
refac out of test
Scope out other enddex points
small lints
Event feedback changes
API mapping updates
Add block and event index to API
set fee bps
use reserve calculation from SDK
decimalize outputs
Delete this sentence and add a description that explains what changes you have
done and why they were necessary.
Delete this sentence and provide a description of how to test the changes in
this PR.
> Add endpoints for Dexscreener support #422

- src/typescript/frontend/src/configs/local-storage-keys.ts
- src/typescript/frontend/src/utils/geolocation.ts
This PR updates the geoblocking logic to handle cases where either the country or the region is not set.
| Case | Action taken |
| ---- | ------------ |
| country === `undefined` && region === `undefined` | geoblocked |
| country === `undefined` && region !== `undefined` | geoblocked if the region is restricted or the country of the region is restricted |
| country !== `undefined` && region === `undefined` | geoblocked if the country is restricted or a region in that country is restricted |
| country !== `undefined` && region !== `undefined` | geoblocked if the country is restricted or the region is restricted |
Additionally, all cache is now versionned using semantic versionning.
All previously present cache is assumed to be `1.0.0`.
When a major version changes, the cache is …
> [ECO-2612] Fix geoblocking logic

- src/typescript/frontend/src/app/dexscreener/asset/route.ts
- src/typescript/frontend/src/app/dexscreener/events/route.ts
- src/typescript/frontend/src/app/dexscreener/latest-block/route.ts
- src/typescript/frontend/src/app/dexscreener/pair/route.ts
- src/typescript/sdk/src/markets/utils.ts
- src/typescript/sdk/src/utils/utility-types.ts
- src/typescript/sdk/tests/e2e/calculate-curve-price.test.ts
> [ECO-2615] Fix the dexscreener endpoints to return floored numbers, set caching policies

- src/typescript/frontend/src/components/svg/icons/LogoIcon.tsx
Going from `0.0.3-alpha` in the `package.json` to `1.0.0` means the `prerelease` field in semver `parse` returns an empty array. Thus, the first element was undefined, and we were calling `.toString()` on it, causing a WSOD.
Fix this by conditionally parsing that part of the semver string.
Visually inspecting the site, make sure it doesn't crash or show a WSOD still. (Already tested locally, will test in preview, too)
> [ECO-2616] Fix prerelease semvar `parse` causing an undefined bug and WSOD

- src/typescript/sdk/src/emojicoin_dot_fun/events.ts
- src/typescript/sdk/src/emojicoin_dot_fun/utils.ts
- src/typescript/sdk/tests/e2e/queries/equality-checks.ts
I've added tests to check that the `event_index` comes in as expected, according to the fullnode JSON response.
> [ECO-2619]  Bump the processor submodule to include the new indexer logic for `event_index`; add simple checks in e2e tests to verify correctness

- src/move/emojicoin_arena/sources/emojicoin_arena.move
1. Add `TopExits` onchain PnL tracking.
1. Use compound assignment operators now that they are supported by `movefmt`
1. Change default melee time to 20 hours since there is no lock-in period.
```sh
git ls-files | entr -c sh -c " \
aptos move compile --dev --move-2  &&
aptos move fmt \
"
```
> [ECO-2641] Add top exits tracking, assorted tweaks

- src/typescript/frontend/src/lib/hooks/use-calculate-swap-price.ts
This PR fixes the price not getting calculated on first swap.
If no swap existed for a market, the calculation was assuming that the swap was
NOT starting in the bonding curve. This does not seem to be accurate, as the
first swap should be in the bonding curve. Switching `startsInBondingCurve`
from `false` to `true` for the first swap seems to fix this issue.
Addresses #488.
Register a market on testnet and try swapping.
> [ECO-2639] Fix price not getting calculated on first swap

- src/move/emojicoin_arena/Move.toml
- src/move/emojicoin_arena/sources/emojicoin_arena.move
- src/move/emojicoin_arena/tests/tests.move
- src/move/test_coin_factories/yin_yang/Move.toml
- src/move/test_coin_factories/yin_yang/sources/coin_factory.move
- src/move/test_coin_factories/zebra/Move.toml
- src/move/test_coin_factories/zebra/sources/coin_factory.move
- src/move/test_coin_factories/zombie/Move.toml
- src/move/test_coin_factories/zombie/sources/coin_factory.move
I initially began working on this PR while its base branch from #478 was
awaiting review. In doing so I began to make some changes to production logic
that I noticed as a result of starting to write tests.
However, in parallel #478 underwent considerable review and so after finalizing
changes there, I rebased this PR so that it could merge in the logic changes
that I had started working on, which were created as a result of test fixturing.
The result is a final prototype complete with view functions, that can then be
merged in a final review of #478.
1. Add view functions and return unpackers for all core structs.
1. Add test-only fixturing to enable comprehensive state/event mocking.
1. Add assorted mocking assertion functions.
1. Add additional test coin factories for `init_module` …
> [ECO-2620] View functions, preliminary testing

- src/typescript/example.env
- src/typescript/frontend/src/app/dev/verify_api_keys/page.tsx
- src/typescript/frontend/src/app/home/page.tsx
- src/typescript/frontend/src/app/market/[market]/page.tsx
- src/typescript/frontend/src/components/pages/emojicoin/components/main-info/MainInfo.tsx
- src/typescript/frontend/src/components/pages/home/components/main-card/MainCard.tsx
- src/typescript/frontend/src/components/pages/home/components/table-card/TableCard.tsx
- src/typescript/frontend/src/context/AptPrice.tsx
- src/typescript/frontend/src/hooks/use-usd-market-cap.ts
- src/typescript/frontend/src/lib/queries/get-apt-price.ts
- src/typescript/frontend/src/lib/server-env.ts
This PR denominates market cap on the home page and the market page in USD.
It uses CoinMarketCap to get the APT price in USD and falls back to showing prices in APT if the price cannot be queried.
Go to market page and home page on vercel.
> [ECO-2573] Denominate market cap in usd

- src/typescript/frontend/src/components/button/index.tsx
- src/typescript/frontend/src/components/header/components/mobile-menu/index.tsx
- src/typescript/frontend/src/components/header/wallet-button/ConnectWalletButton.tsx
- src/typescript/frontend/src/components/pages/emojicoin/components/main-info/MainInfo.tsx
This PR sets the width of button to a fix size, to avoid the buttons changing size when the scrable animation happens. This prevents elements (especially in flexes) to shift around.
Check all buttons hover animation.
> [ECO-2650] Fix size of scramble to avoid elements moving

- src/typescript/frontend/package.json
Bumps the frontend version to 1.1.0, since some of the changes (like the CoinGecko API and USD denomination) are technically breaking changes in terms of the setup / infrastructure / env variables used.
> [ECO-2607] Bump frontend version

- cfg/cspell-dictionary.txt
- src/move/emojicoin_arena/Move.toml
- src/move/emojicoin_arena/README.md
- src/move/emojicoin_arena/sources/emojicoin_arena.move
- src/move/emojicoin_arena/sources/pseudo_randomness.move
- src/move/emojicoin_arena/tests/tests.move
- src/move/test_coin_factories/yin_yang/Move.toml
- src/move/test_coin_factories/yin_yang/sources/coin_factory.move
- src/move/test_coin_factories/zebra/Move.toml
- src/move/test_coin_factories/zebra/sources/coin_factory.move
- src/move/test_coin_factories/zombie/Move.toml
- src/move/test_coin_factories/zombie/sources/coin_factory.move
This PR finalizes the Emojicoin Arena Move prototype, adding a README with a
comprehensive design overview.
Per extensive review, it adopts a lightweight data model that provides only the
minimal amount of information to required to enable comprehensive indexing,
as discussed in detail in the README.
1. Add assorted inner abstractions to ease the review process.
1. Eliminate `SmartTable` structs since they can be a DoS vector.
1. Remove fields, events that are not required for lightweight data model.
1. Require that if a user has locked in since their most recent to an empty
escrow, they must select lock in on subsequent top-off operations.
1. Allow user to elect lock-in even if they do not ultimately get matched, to
prevent unexpected abortions.
1. Add exchange rate calculations.
1. …
> [ECO-2618] Finalize emojicoin arena core logic design

- src/move/emojicoin_arena/sources/emojicoin_arena.move
- src/move/emojicoin_arena/tests/tests.move
1. Add view function for inspecting match amount when locking in, associated
aborts and inline refactors.
1. Make exchange rate view function public.
1. Add aborts for escrow and melee views.
1. Consolidate logic for checking if melee is active.
1. Clarify constant names for single/double route fee rates.
1. Test exchange rate helper.
1. Test expected failure for escrow note existing.
1. Add happy path test for entering, swapping inside of, and exiting a melee.
1. Add helper for simulating a swap before executing an escrow operation.
Tested to ~50% coverage per running in `src/move/emojicoin_arena`:
```sh
git ls-files | entr -c sh -c " \
aptos move test --coverage --dev --move-2  &&
aptos move fmt \
"
```
> [ECO-2651] Add emojicoin arena initial happy path testing

- src/move/emojicoin_arena/sources/emojicoin_arena.move
- src/move/emojicoin_arena/tests/tests.move
1. Remove underflow check for inner match amount function that is unreachable
during runtime.
1. Add view function to check if an escrow exists.
1. Add helpers to mutate values in a given melee.
1. Add helper(s) to init module with a funded participant.
1. Hit coverage on assorted expected failure tests.
1. Extend happy path swap test with functionality on other side.
1. Add test to hit coverage on match amount logic.
Tested to ~70% coverage per running in `src/move/emojicoin_arena`:
```sh
git ls-files | entr -c sh -c " \
aptos move test --coverage --dev --move-2  &&
aptos move fmt \
"
```
> [ECO-2657] Add arena match amount, expected failure testing

- src/move/emojicoin_arena/sources/emojicoin_arena.move
- src/move/emojicoin_arena/tests/tests.move
1. Implement abortion for no funds when swapping, exiting.
1. Abstract prologue function for local variable setup in `swap`, `exit` APIs.
done and why they were necessary.
1. Refactor epilogue abstraction for exiting escrow.
1. Abstract tap out fee assessment.
1. Abstract withdrawing coins from escrow.
1. Alphabetize functions.
1. Update crank helper functions to support locking in, melee side. 
1. Add test for cranking via a locked swap, on opposite side from existing test.
1. Add assorted minor expected failure tests.
1. Add test for setting new durations on successive melees.
Tested to 100% coverage from within `src/move/emojicoin_arena`:
```sh
git ls-files | entr -c sh -c " \
aptos move test --coverage --dev --move-2 &&                              
aptos move fmt
"
```
> [ECO-2659] Add final arena abstractions, tests to 100% coverage

- src/move/emojicoin_arena/README.md
Update emojicoin arena README:
1. Remove PnL pseudo code now that it is covered in ongoing indexing
1. Add section with publish commands, filing https://github.com/aptos-labs/aptos-core/issues/15769
1. Published on testnet: https://explorer.aptoslabs.com/txn/6596176228?network=testnet
> [ECO-2666] Update arena README publish, PnL sections

- src/typescript/frontend/src/app/coingecko/historical_trades/route.ts
- src/typescript/frontend/src/app/coingecko/tickers/route.ts
- src/typescript/frontend/src/app/coingecko/tickers/utils.ts
This PR adds the routes CoinGecko needs to list emojicoin.fun
Query both routes on the `/coingecko` parent route.
> [ECO-2631] Add coingecko routes

- src/typescript/frontend/src/components/header/wallet-button/ConnectWalletButton.tsx
- src/typescript/frontend/src/components/pages/launch-emojicoin/memoized-launch/components/launch-or-goto.tsx
The go to emojicoin market button doesn't show up if the user isn't connected with their wallet or if they're geoblocked. This can be fixed by adding a simple "forceDisplayChildren" prop to the ConnectWalletButtonFallback, with the conditional set to whether or not the market is registered already.
BEFORE CHANGE:
AFTER CHANGE (see wallet is definitively not connected in the top right):
Delete this sentence and provide a description of how to test the changes in
this PR.
> [ECO-2710] Force display the "Go to emojicoin market" button on the launch emojicoin page regardless of wallet connection or being geoblocked

- src/cloud-formation/deploy-indexer-fallback.yaml
- src/cloud-formation/deploy-indexer-main.yaml
- src/cloud-formation/deploy-indexer-production.yaml
Recent migration change for a couple fields needs to be merged.
To do a hot upgrade, this simply needs to bump the version number to the newest tag (3.0.1) in the yaml config files.
> [ECO-2724] Hot upgrade processor and broker on `emoji-main` (testnet) to `3.0.1`; for the arena view `NUMERIC` column casts

- .github/workflows/push-deployer.yaml
- src/docker/deployer/Dockerfile
- src/docker/deployer/sh/build-publish-payloads.sh
- src/docker/deployer/sh/compare-addresses.sh
- src/docker/deployer/sh/entrypoint.sh
- src/docker/deployer/sh/init-profile.sh
- src/docker/localnet/Dockerfile
The CLI version needs to bump now that AMD/ARM successfully built the CLI v6.0.1.
And the arena code needs to deploy for local testing because it uses `--move-2`.
> [ECO-2725] Update `localnet` and `deployer` to use Aptos CLI `v6.0.1`

- src/typescript/sdk/tests/e2e/broker/websockets.test.ts
The WebSockets e2e test keeps failing. I investigated why and I believe the issue is occurring because a `PeriodicStateEvent` is emitted *sometimes*. This is because the 1-minute period boundary for the initial market registration begins at different points in the minute.
That is, if the market is registered at 5 seconds after a 1m period boundary, the full test can run in 55 seconds and not emit a periodic state event, thus succeeding, because the # of events received by the client from the broker is exactly the amount expected.
However, if the market is registered at 55 seconds after a 1m period boundary, the test may take longer than 5 seconds and thus a periodic state event is emitted alongside the swap/chat event for the market.
To fix this, I simply narrowed the event types filter …
> [ECO-2727] Fix flaky websockets e2e test by explicitly not subscribing to `PeriodicStateEvents`

- src/typescript/sdk/package.json
Didn't realize `0.3.0` had already been published, so bump to `0.4.0`, merge and publish it
> [ECO-2738] Bump SDK package version to `0.4.0`; processor submodule to `4.0.1`

- src/typescript/frontend/src/components/pages/emojicoin/components/trade-emojicoin/SwapComponent.tsx
- src/typescript/frontend/src/lib/hooks/use-calculate-swap-price.ts
The calculations for the swap price were using the market's last swap state incorrectly.
`startsInBondingCurve` was checking the `lastSwap` event's `startsInBondingCurve` value, which is only accurate if the `lastSwap` did *NOT* cause the market to exit the bonding curve!
In cases where that is true, the price simulation would fail, and often it'd result in "min swap output not met" errors in the txn submission flow.
To fix this, we simply pass the market's latest state and use those values to calculate the exact curve price, rather than the last swap values.
This wasn't caught in SDK tests unfortunately simply because the inputs to the function were given incorrectly- that is, "lastSwapEvent"'s state was being used, instead of the current market state's state.
Tested manually several …
> [ECO-2744] Fix swap price calculation right after bonding curve transition

- cfg/cspell-config.json
- src/typescript/sdk/src/emojicoin_dot_fun/serialize-args-to-json.ts
- src/typescript/sdk/tests/unit/serialize-args-to-json.test.ts
Had this stashed away for a bit, just decided to finally add it in with some simple tests to ensure it works
This facilitates using deeply nested/complex entry function argument types with the wallet adapter
Finally got rid of that pesky `TODO`!
Added sdk unit tests just for it!
> [ECO-2746] Refactor JSON serialization of Move values to be simpler and work for deeply nested values

- src/typescript/frontend/COINGECKO.md
- src/typescript/frontend/src/app/coingecko/historical_trades/route.ts
- src/typescript/frontend/src/app/coingecko/tickers/route.ts
This PR adds a `COINGECKO.md` file to help CoinGecko integrate our API into their system.
It also fixes an off-by-one error in the `limit` and `skip` calculations of the tickers endoint.
It also adds the `skip` field to the historical trades field to allow querying all the trades.
Try `/coingecko/tickers` and `/coingecko/historical_trades` with the info in `COINGECKO.md`.
> [ECO-2731] Add CoinGecko README doc and fix small API issues

- src/typescript/frontend/public/locales/en-US.json
- src/typescript/frontend/src/components/pages/launch-emojicoin/memoized-launch/components/launch-or-goto.tsx
- src/typescript/frontend/src/components/pages/launch-emojicoin/memoized-launch/index.tsx
For some reason, I removed this check a while back. I'm adding it back in because it's confusing UX wise and it's an easy fix.
Just tested on my local network with and without an insufficient balance and made sure any updates properly work.
> [ECO-2751] Don't let a user register if they have insufficient balance, make error message clearer; bump processor submodule

- src/typescript/frontend/src/components/header/components/menu-item/index.tsx
- src/typescript/frontend/src/components/header/components/menu-item/types.ts
- src/typescript/frontend/src/components/header/components/mobile-menu/index.tsx
- src/typescript/frontend/src/components/header/constants.ts
- src/typescript/frontend/src/components/header/index.tsx
- src/typescript/frontend/src/middleware.ts
- src/typescript/frontend/src/router/routes.ts
- Note that this wasn't necessary, since everything fits at the smallest width where the header items are displayed now. See below.
> [ECO-2747] Refactor header items for new cult page

- src/typescript/frontend/src/app/cult/page.tsx
Exclusively enable the `/cult` page in development and preview Vercel environments
Try visiting it
> [ECO-2771] Exclusively enable the `/cult` page in `development` and `preview` Vercel environments

- src/cloud-formation/README.md
- src/cloud-formation/cold-upgrade.sh
- src/cloud-formation/deploy-indexer-alpha.yaml
- src/cloud-formation/deploy-indexer-fallback.yaml
- src/cloud-formation/deploy-indexer-main.yaml
- src/cloud-formation/deploy-indexer-production.yaml
- src/cloud-formation/indexer.cfn.yaml
1. Delete `DeployStack` parameter since it is unused.
1. Add `cold-upgrade.sh` script with README.
1. Downgrade `production` and `fallback` binaries to current versions from
`production` branch, `4.0.2`.
1. Change `main` environment to `alpha` to more clearly conform to standard
release schedule nomenclature, especially since a new `emojicoin-arena`
feature branch will be used for `alpha` indexer builds.
1. Pending `alpha` release testing.
> [ECO-2783] Refactor indexer for new release schedule

- src/rust/broker/README.md
- src/rust/broker/src/processor_connection.rs
- src/rust/broker/src/types.rs
- src/rust/broker/src/util.rs
Although keep in mind this is already tested and in use for SDK tests in the coming PRs.
Already tested in a different PR- merging to `arena` out of order for clarity's sake.
- Note that tests will come in a PR after this, although they've already been written and used.
> [ECO-2784] Add arena events to the broker, update subscription model and README to support `arena`

- src/typescript/frontend/src/app/home/page.tsx
- src/typescript/frontend/src/lib/queries/num-market.ts
- src/typescript/sdk/src/indexer-v2/queries/app/home.ts
- src/typescript/sdk/tests/e2e/queries/num-markets.test.ts
For some reason, `count: "exact", head: "true"` with no actual rows returned does not work.
Note this query was generally not used, so it's been fine for now. I'm fixing it in case it's ever actually used in the fallback scenario.
Added a test for equality of the two (largest market ID and # markets registered) in the SDK tests.
> [ECO-2800] Fix the fallback number of markets query

- src/cloud-formation/deploy-indexer-alpha.yaml
Merely bumping the built image here so that the `alpha` stack will use the new broker version with arena event support.
See #565 
See #567
> [ECO-2789] Update the broker image version for the `alpha` stack to use `5.0.1`: arena event emission support

- cfg/cspell-frontend-dictionary.txt
- src/typescript/frontend/next.config.mjs
- src/typescript/frontend/src/app/home/HomePage.tsx
- src/typescript/frontend/src/app/home/page.tsx
- src/typescript/frontend/src/app/layout.tsx
- src/typescript/frontend/src/components/RandomEmojiBg.tsx
- src/typescript/frontend/src/components/button/index.tsx
- src/typescript/frontend/src/components/button/types.ts
- src/typescript/frontend/src/components/pages/home/components/arena-card/index.tsx
- src/typescript/frontend/src/components/pages/home/components/arena-card/module.css
- src/typescript/frontend/src/components/pages/home/components/emoji-table/index.tsx
- src/typescript/frontend/src/components/pages/home/components/table-card/TableCard.tsx
- src/typescript/frontend/src/components/pages/launch-emojicoin/animated-emoji-circle/index.tsx
- src/typescript/frontend/src/router/routes.ts
This PR updates the home page for the new arena feature.
See home page.
> [ECO-2664] Add home page arena update

- src/typescript/frontend/src/app/market/[market]/page.tsx
- src/typescript/frontend/src/components/Badge.tsx
- src/typescript/frontend/src/components/header/components/menu-item/index.tsx
- src/typescript/frontend/src/components/header/components/menu-item/types.ts
- src/typescript/frontend/src/components/header/components/mobile-menu-item/index.tsx
- src/typescript/frontend/src/components/header/components/mobile-menu-item/types.ts
- src/typescript/frontend/src/components/header/components/mobile-menu/index.tsx
- src/typescript/frontend/src/components/header/constants.ts
- src/typescript/frontend/src/components/header/index.tsx
- src/typescript/frontend/src/components/pages/emojicoin/ClientEmojicoinPage.tsx
- src/typescript/frontend/src/components/pages/emojicoin/types.ts
- src/typescript/frontend/src/components/svg/icons/LogoIcon.tsx
- src/typescript/frontend/src/router/routes.ts
This PR adds a banner on the markets where a melee is in progress.
It also adds the buttons in the mobile menu and the desktop top navigation bar that link to the arena, as the banner instructs the user to click on the latter.
Go to the market page of a market that is in melee.
> [ECO-2588] Add market page banner and navigation link to arena

- src/typescript/frontend/src/hooks/use-usd-market-cap.ts
The UI gets very crowded with all the numbers, the decimals don't matter at that size market cap.
None
> Make USD market cap hide decimals when > $1M

- src/typescript/frontend/package.json
- src/typescript/frontend/src/app/global.css
- src/typescript/frontend/src/components/ui/Button.tsx
- src/typescript/frontend/src/components/ui/Input.tsx
- src/typescript/frontend/src/components/ui/Label.tsx
- src/typescript/frontend/tailwind.config.js
- src/typescript/frontend/tsconfig.json
- src/typescript/pnpm-lock.yaml
Adds shadcn styles to `global.css` and tailwind utilities so we can use shadcn components while prototyping and in test
> [ECO-2828] Add shadcn styles to `global.css` for prototyping

- .github/workflows/conventional-commits.yaml
Add a GitHub action to verify that PR messages conform to conventional commits with an `ECO-XXXX` tag for the scope
GitHub checks verified for pushing changes as well as for changing the PR title
> ci(ECO-2840): Add conventional commit check

- src/cloud-formation/deploy-indexer-alpha.yaml
- src/cloud-formation/deploy-indexer-fallback.yaml
- src/cloud-formation/deploy-indexer-production.yaml
- src/cloud-formation/indexer.cfn.yaml
1. Add `IndexArena` parameter for configurable indexing
1. Passes `cfn-lint`
1. When this merges, the environment variable for `emoji-alpha` should be toggled off and arena events shouldn't get parsed, then with a subsequent cold upgrade and variable toggle it should be set again and index as expected
> feat(ECO-2837): Add configurable arena indexing

- .github/workflows/submodule.yaml
Disable the submodule check for PRs that are not into `main`.
See this PR's checks
> ci(ECO-2482): Disable submodule check when PR not to main

- src/typescript/frontend/src/lib/utils/user-agent-selectors.ts
This removes like 40,000 console errors in local development. Otherwise, functionally exactly the same.
Tested locally. Makes no difference functionally ultimately.
> fix(ECO-2845): Don't try to parse user agent string if it's empty

- src/cloud-formation/deploy-indexer-alpha.yaml
Remove the override to disable arena indexing, thus allowing a cold upgrade with fully-indexed arena data
> chore(ECO-2847): Remove disabling arena indexing override

- src/typescript/frontend/src/app/test-utils/page.tsx
- src/typescript/frontend/src/components/pages/test-utils/SetNewMeleeDuration.tsx
- src/typescript/frontend/src/components/pages/test-utils/index.ts
- src/typescript/frontend/src/components/pages/test-utils/market-address-conversion/MarketAddressConversion.tsx
- src/typescript/frontend/src/components/pages/test-utils/market-address-conversion/index.ts
- src/typescript/frontend/src/components/pages/test-utils/market-address-conversion/use-market-address-view.ts
- src/typescript/frontend/src/lib/store/server-to-client/StoreOnClient.tsx
- src/typescript/frontend/src/router/routes.ts
- src/typescript/sdk/src/markets/arena-utils.ts
- src/typescript/sdk/src/markets/index.ts
Entirely just test stuff and component prototyping, most of the PR lines changed comes from `pnpm-lock.yaml`.
https://github.com/user-attachments/assets/0e530e22-3730-460e-9ec0-3728d8943cf5
> feat(ECO-2813): Add a `/test-utils` page for local/testnet utilities

- src/typescript/frontend/src/components/charts/BrowserNotSupported.tsx
- src/typescript/frontend/src/components/charts/PrivateChart.tsx
- src/typescript/frontend/src/components/charts/get-bars.ts
- src/typescript/frontend/src/components/charts/trading-view-utils.ts
I will compare the contents of the bars in the chart and on-state by comparing market data for the same market, both locally with mainnet indexer data on this branch, and with mainnet indexer data using the `main` branch for the private chart.
I did this by console logging the `bars` value in both builds running concurrently, one on port 3001 and another on port 3002.
I then stored them as variables by right clicking in Chrome, and clicking `Copy as object`. I stored them as `newData` and `oldData`.
Then I did a simple JSON.stringify to compare:
```typescript
JSON.stringify(newData) === JSON.stringify(oldData);
```
> chore(ECO-2851): Clean up `PrivateChart.tsx` and make the inner logic more modular

- src/typescript/sdk/tests/e2e/arena/general/arena.test.ts
Didn't realize SDK tests weren't necessary for merging, so GitHub auto-merged a PR with failing tests.
Ensure tests pass, then merge.
> test(ECO-2853): Fix object comparison in e2e tests that accidentally got merged

- src/typescript/sdk/src/indexer-v2/queries/index.ts
- src/typescript/sdk/src/indexer-v2/queries/misc/fetch-specific-markets.ts
- src/typescript/sdk/src/indexer-v2/queries/misc/index.ts
- src/typescript/sdk/src/utils/misc.ts
- src/typescript/sdk/tests/e2e/queries/specific-markets.test.ts
- src/typescript/sdk/tests/unit/chunk.test.ts
Since this query is used in both the stats PR #574 and PR #606, I extracted it out of the stats PR and added tests for it.
@0xForkh tagging you here, feel free to review the PR or just look it over so you can use it in #606 
Lots of testing to ensure it works as expected with no errors, even with really large query URLs (with chunking), although the console will log a warning if more than 100 market symbols are passed.
> test(ECO-2854): Add `fetchSpecificMarkets` query with chunking and unit/e2e tests

- .github/workflows/verify-doc-site-build.yaml
Update the docs site build to run on each PR, so it can easily be used as a required status check. It still takes less time than SDK/pre-commit actions which run in parallel, so it should not inhibit overall CI time.
CI
> ci(ECO-2870): Update docs site build to run each PR

- src/typescript/frontend/src/components/FormattedNumber.tsx
- src/typescript/frontend/src/components/pages/home/components/table-card/animation-variants/event-variants.ts
- src/typescript/frontend/src/hooks/use-label-scrambler.ts
> chore(ECO-2872): Move `useLabelScrambler` to a sensible location

- src/typescript/frontend/next.config.mjs
Remove the opinionated default `nextjs 14` caching behavior- update it to match the default behavior in `nextjs 15`: see [here](https://nextjs.org/docs/app/api-reference/config/next-config-js/staleTimes#version-history)
This change was actually supposed to be flipped on a while ago, it just never got in on accident. This will fix a lot of confusing ux/ui behavior where data seems stale from the server despite a proper caching revalidation time.
Tested manually with the `test-utils` functions. Works pretty well.
> fix(ECO-2848): Update `next.config.mjs` `experimental.staleTimes` to remove opinionated default caching behavior

- src/typescript/frontend/src/components/pages/emojicoin/components/main-info/MainInfo.tsx
Simply removes dexscreener button from market page
Not much to test. The whole top section looks better with the button off as it eliminates a row.
Here is a screenshot of the change. Left is production version, right is with changes from this branch.
> feat(ECO-2886): Take out dex screener from market metadata badge

- src/docker/README.md
Fix a `docker compose up` command in the Docker README, pointed out as broken by @RomanHodulak
> docs(ECO-2917): Fix Docker README compose up command

- src/typescript/sdk/README.md
It's been a long time coming! Added proper examples for using the SDK. Nothing super fancy, but we can point users at it now.
Relies on #645 to work properly.
Ran all the examples manually, although I'll do it again before submitting.
> docs(ECO-2911): Add a `README.md` to the SDK

- src/typescript/frontend/src/components/pages/wallet/PortfolioRow.tsx
Fairly self-explanatory.
Tested on a local build
> fix(ECO-2920): Display market cap in USD on My Emojicoins page unless APT price isn't available

- src/typescript/frontend/src/components/pages/emojicoin/components/main-info/MainInfo.tsx
- src/typescript/frontend/src/components/pages/emojicoin/components/mobile-grid/index.tsx
- src/typescript/frontend/src/components/pages/emojicoin/components/mobile-grid/styled.tsx
- src/typescript/frontend/src/components/pages/wallet/WalletClientPage.tsx
- src/typescript/frontend/src/components/ui/table/ecTableBody.tsx
- src/typescript/frontend/src/components/ui/table/table.tsx
Fixes and minor improvements on mobile.
Having an absolute positionned td inside of the tr to handle the hover effect was causing issues on some devices/browsers.
I managed to have the hover-effect working without needing the absolutely-positioned td.
Additionnaly, I took the liberty to reduce the horizontal padding on mobile for the market page.
> fix(ECO-2918): Fix trade history and my emojicoins on mobile

- src/typescript/frontend/src/app/api/trending/route.ts
- src/typescript/frontend/src/app/home/page.tsx
- src/typescript/frontend/src/components/charts/PrivateChart.tsx
- src/typescript/frontend/src/lib/queries/price-feed.ts
- src/typescript/frontend/src/lib/utils/decimals.ts
- src/typescript/frontend/src/router/routes.ts
- src/typescript/sdk/src/indexer-v2/queries/api/index.ts
- src/typescript/sdk/src/indexer-v2/queries/api/trending.ts
- src/typescript/sdk/src/indexer-v2/queries/index.ts
- src/typescript/sdk/src/indexer-v2/types/index.ts
- src/typescript/sdk/src/indexer-v2/types/json-types.ts
- src/typescript/sdk/src/utils/hex.ts
- src/typescript/sdk/src/utils/nominal-price.ts
- src/typescript/sdk/src/utils/utility-types.ts
- src/typescript/sdk/tests/unit/hex.test.ts
Misc small fixes
Testing manually and in preview.
> feat(ECO-2928): Add `/api/trending` route

- src/typescript/frontend/src/app/api/trending/route.ts
```shell
March 01 00:42:17, 03-01T00:40:35.77985Z 13345
March 01 00:42:18, 03-01T00:40:35.77985Z 13345
March 01 00:42:19, 03-01T00:41:26.165342Z 13346
March 01 00:42:21, 03-01T00:41:26.165342Z 13346
```
I polled the endpoint every second and watched for cahnges. You can see above that when the market nonce for a market was incremented, it took slightly longer than 10 seconds to see it. Note that the times overall may be slightly out of sync, since the left is my computer time vs the on-chain time.
In general, the data won't stale for longer than ~30 seconds. Since the `revalidate` in the `GET` request path can be out of sync with the revalidation time in the `unstable_cache` `fetch` caches, it's not always exactly 10 seconds. In general, it seems to be roughly 15-25 seconds.
> chore(ECO-2936): Fix default path revalidation time for `/api/trending`; indicate that `market_cap_usd` and `usd_price` might be undefined

- src/typescript/sdk/tests/e2e/arena/general/arena.test.ts
This PR adds E2E tests to test `exited` and `last_exit_0` fields for the arena leaderboard history.
> test(ECO-2835): Test leaderboard exit status

- src/typescript/sdk/src/indexer-v2/queries/app/arena.ts
- src/typescript/sdk/src/indexer-v2/types/index.ts
- src/typescript/sdk/src/indexer-v2/types/json-types.ts
- src/typescript/sdk/src/types/arena-types.ts
- src/typescript/sdk/tests/e2e/arena/candlesticks.test.ts
- src/typescript/sdk/tests/e2e/arena/general.test.ts
- src/typescript/sdk/tests/e2e/arena/utils.ts
This PR uses different account for different tests to avoid test data collision.
> chore(ECO-2914): Use different accounts for different leaderboard tests

- src/rust/broker/README.md
- src/rust/broker/src/types.rs
- src/rust/broker/src/util.rs
- src/typescript/frontend/src/components/pages/arena/ArenaClient.tsx
- src/typescript/frontend/src/hooks/use-reliable-subscribe.ts
- src/typescript/frontend/src/lib/store/websocket/store.ts
- src/typescript/sdk/src/broker-v2/client.ts
- src/typescript/sdk/src/broker-v2/types.ts
- src/typescript/sdk/src/indexer-v2/types/index.ts
- src/typescript/sdk/src/types/arena-types.ts
- src/typescript/sdk/tests/e2e/broker/utils.ts
> feat(ECO-2949): Add `ArenaCandlestick`s to the broker

- src/typescript/README.md
Update a link for the CDN doc in the `common` repo (previously `cloud-infra`)
CI passes
> docs(ECO-2961): Update CDN doc reference for common repo

- src/typescript/frontend/src/app/coingecko/tickers/route.ts
- src/typescript/frontend/src/app/dexscreener/asset/route.ts
- src/typescript/frontend/src/app/stats/TableData.tsx
- src/typescript/frontend/src/components/pages/emojicoin/components/holders/coin-holders.tsx
- src/typescript/frontend/src/components/pages/emojicoin/components/trade-history/trade-history.tsx
- src/typescript/frontend/src/components/pages/wallet/fetch-specific-markets-action.ts
- src/typescript/frontend/src/hooks/use-usd-market-cap.ts
- src/typescript/frontend/src/lib/hooks/queries/use-fetch-owner-emojicoin-balances.ts
- src/typescript/frontend/src/lib/store/event/candlestick-bars.ts
- src/typescript/frontend/src/lib/store/event/utils.ts
- src/typescript/frontend/src/lib/utils/decimals.ts
- src/typescript/frontend/src/lib/utils/format-number-string.ts
`toNominal` was used in the frontend, but in some places in the `sdk` we needed it. I moved it to the SDK a week or so ago, but left it aliased in the frontend to allow other files to continue to import from the original `frontend/src/lib/utils` location to avoid conflicts.
This change only affects imports. Static analysis will report any errors (build time failure)
> chore(ECO-2930): Unalias `toNominal` in `frontend/lib/utils/decimals.ts` and replace with `@sdk/utils`

- src/typescript/frontend/src/components/pages/emojicoin/components/main-info/MainInfo.tsx
- src/typescript/frontend/src/hooks/use-usd-market-cap.ts
This is just estimated, but it gives users a way to determine what their value trading is with less confusion.
Tested locally
> feat(ECO-2993): Add estimated volume in USD based on current APT price

- src/cloud-formation/deploy-indexer-fallback.yaml
- src/cloud-formation/deploy-indexer-production.yaml
Overload the `IndexArena` stack parameter to `false` for production and fallback
Tested during development in #608
> chore(ECO-3005): Disable production/fallback arena indexing

- src/cloud-formation/deploy-indexer-fallback.yaml
- src/cloud-formation/deploy-indexer-production.yaml
- src/docker/compose.yaml
Bump broker binaries to `v6.0.0`, processor to `v6.0.1` in `compose.yaml`, deploy files, and submodule
SDK tests in CI
> chore(ECO-3011): Bump indexer binary versions in `compose.yaml`, deploy files, submodule

- src/typescript/frontend/src/app/market/[market]/page.tsx
In general we should be catching errors and providing default values where possible in the higher level server components to avoid a single fetch taking the rest of the page down with it.
I noticed this while using `testnet` queries with the `fetchTopHolders`, where the fetch often fails. If this does happen- we merely want to log it and return an empty value.
Here I add default values to the following:
NOTE: The only one this isn't possible for (currently) is the `marketView`, since it utilizes state from on-chain (current `PeriodicStateTrackers`, not in the database), so that one is left alone.
I'll test it locally with a failed fetch.
> fix(ECO-3018): Catch fetch errors on `[market]/page.tsx`

- src/rust/broker/README.md
- src/rust/broker/src/types.rs
- src/rust/broker/src/util.rs
- src/typescript/frontend/src/app/api/candlesticks/search-params-schema.ts
- src/typescript/frontend/src/app/home/HomePage.tsx
- src/typescript/frontend/src/components/pages/arena/ArenaClient.tsx
- src/typescript/frontend/src/components/pages/home/components/SubscribeToHomePageEvents.tsx
- src/typescript/frontend/src/components/pages/home/components/emoji-table/index.tsx
- src/typescript/frontend/src/hooks/use-latest-melee-id.ts
- src/typescript/frontend/src/hooks/use-reliable-subscribe.ts
- src/typescript/frontend/src/lib/store/arena/store.ts
- src/typescript/frontend/src/lib/store/arena/utils.ts
- src/typescript/frontend/src/lib/store/event/event-store.ts
- src/typescript/frontend/src/lib/store/event/types.ts
- src/typescript/frontend/src/lib/store/event/utils.ts
- src/typescript/frontend/src/lib/store/websocket/store.ts
- src/typescript/sdk/src/broker-v2/client.ts
- src/typescript/sdk/src/broker-v2/types.ts
- src/typescript/sdk/src/indexer-v2/types/index.ts
- src/typescript/sdk/src/types/arena-types.ts
- src/typescript/sdk/tests/e2e/broker/utils.ts
- src/typescript/sdk/tests/e2e/broker/websockets.test.ts
This PR adds arena broker events to the global state store (`zustand` implementation).
This allows us to detect when new melees begin and in general when any arena event happens in the frontend in the form of an event-driven pubsub architecture
It also previously merged the arena candlesticks additions as well (originally a separate PR).
Using in all my PRs, manual testing.
> feat(ECO-2874): Add arena broker events to the state store [2/4]

- src/typescript/frontend/src/app/api/arena/candlesticks/fetch.ts
- src/typescript/frontend/src/app/api/arena/candlesticks/route.ts
- src/typescript/frontend/src/app/api/arena/candlesticks/search-params-schema.ts
- src/typescript/frontend/src/app/api/candlesticks/utils.ts
- src/typescript/frontend/src/components/charts/get-bars.ts
- src/typescript/frontend/src/components/pages/arena/ArenaClient.tsx
- src/typescript/frontend/src/lib/store/arena/utils.ts
- src/typescript/frontend/src/lib/store/event/candlestick-bars.ts
- src/typescript/frontend/src/lib/store/event/event-store.ts
- src/typescript/frontend/src/lib/store/event/types.ts
- src/typescript/frontend/src/lib/store/event/utils.ts
- src/typescript/frontend/src/router/routes.ts
- src/typescript/sdk/src/const.ts
- src/typescript/sdk/src/emojicoin_dot_fun/arena-events.ts
- src/typescript/sdk/src/indexer-v2/queries/app/arena.ts
- src/typescript/sdk/src/indexer-v2/types/index.ts
- src/typescript/sdk/src/types/arena-types.ts
- src/typescript/sdk/src/utils/misc.ts
- src/typescript/sdk/tests/unit/period-boundaries.test.ts
- src/typescript/sdk/tests/utils/calculate-periodic-boundaries-crossed.ts
Lots of the changes for the new arena candlesticks are simply because the new ArenaPeriod type wasn't properly unioned with Period (on my advice).
I've fixed them to work everywhere applicable so that the utility functions for `Period` types work with both types, but also still requiring that they specifically should only be the base `Period` (non `Arena Period`) type where applicable.
Lots of mostly type changes here, but I've been using it in #619 
> chore(ECO-3045): Add the new `/api/arena/candlesticks` route; properly implement `Period | ArenaPeriod` types [3.2/4]

- src/rust/broker/README.md
- src/rust/broker/src/server/sse.rs
- src/rust/broker/src/server/ws.rs
- src/rust/broker/src/types.rs
- src/rust/broker/src/util.rs
- src/typescript/frontend/src/components/charts/const.ts
- src/typescript/frontend/src/components/charts/get-bars.ts
- src/typescript/frontend/src/hooks/use-reliable-subscribe.ts
- src/typescript/frontend/src/lib/store/event/types.ts
- src/typescript/frontend/src/lib/store/websocket/store.ts
- src/typescript/sdk/README.md
- src/typescript/sdk/src/broker-v2/client.ts
- src/typescript/sdk/src/broker-v2/types.ts
- src/typescript/sdk/tests/e2e/broker/utils.ts
Instead of just a boolean flag, enforce that the broker only accepts a single period type for a subscription to arena candlestick events. Otherwise, the broker sends out 6+ messages to every client on each arena swap.
This way, it only sends out one candlestick per client subscription, based on the period they subscribe to.
> feat(ECO-3028): Add support for granular arena period subscriptions in the broker [3.3/4]

- src/typescript/frontend/src/components/pages/home/components/main-card/module.css
Emojis have a much taller line-height than their font size. Normally we set the line height to be manually a larger value than the font size, but these were added manually when we updated them to support multi-emoji symbols.
The fix is simple- just pass a line-height of `1.5em` to ensure the emojis don't get clipped.
Video on slack, tested on safari alerady. Too big to link the video here though
> fix(ECO-3053): Fix emoji clipping on Safari on the trending markets card

- src/rust/broker/src/types.rs
- src/rust/broker/src/util.rs
This PR may get split up later but for now it is a way to track the following things necessary to use the new candlesticks:
Lots of manual testing. Rust unit tests cover lots of the logic as well
> feat(ECO-3027): Add candlestick type support to broker

- src/typescript/frontend/package.json
- src/typescript/sdk/package.json
> chore(ECO-3061): Bump the frontend to `1.6.0` and SDK to `0.5.4`

- src/typescript/frontend/src/components/misc/background-emojis/BackgroundEmojis.tsx
- src/typescript/frontend/src/context/ContentWrapper.tsx
> fix(ECO-3056): Fix/clean up the BackgroundEmojis component

- src/cloud-formation/deploy-indexer-fallback.yaml
- src/cloud-formation/deploy-indexer-production.yaml
Remove the `IndexArena` flag that currently overloads arena indexing on production and fallback stacks.
Note that without the flag set to false it defaults to indexing arena events.
The overload flag in question is already removed from the alpha stack, which has been tested extensively.
> chore(ECO-3090): Remove arena index disable flag

- src/typescript/frontend/src/app/home/page.tsx
TypeScript closures work in an odd way- they don't necessarily check that a variable has already been declared in a promise closure, because it can technically be executed later.
This meant that accidentally using `meleeData` before it was even declared didn't result in an error at compile/build time.
Simple fix:
Tested it locally already.
> fix(ECO-3091): Fix arena hero section not showing up

- src/typescript/frontend/src/lib/store/arena/utils.ts
The function to store the bar data in state was only being called in the else block. To fix it, just needed to move it down a line outside of the if/else, so it always updates with whatever the new current latest bar is.
> fix(ECO-3092): Fix first arena candlestick in state not being updated

- src/typescript/frontend/package.json
- src/typescript/pnpm-lock.yaml
> chore(ECO-3118): Bump `next.js` to `14.2.25`

- src/typescript/frontend/src/components/misc/background-emojis/BackgroundEmojis.tsx
- src/typescript/frontend/src/components/misc/background-emojis/use-window-size-with-step.ts
See the videos attached below for the difference and explanation (it's fairly obvious):
https://github.com/user-attachments/assets/7babe320-6350-43d5-b51f-3a02e57f9bb3
> fix(ECO-3127): Only regenerate background emojis on a step interval to avoid excessive re-renders

- src/typescript/sdk/jest.config.js
- src/typescript/sdk/src/utils/account-address.ts
- src/typescript/sdk/tests/unit/hex.test.ts
- src/typescript/sdk/tests/unit/serialize-entry-args-to-json.test.ts
The new TS SDK 1.37.1 (upgrading from 1.27.0, so it might be some version in between) added a requirement to `AccountAddress` conversions that the number of input hex characters must be at least 60. This wasn't previously there, so we must pad all of our addresses with as many 0s as possible before converting to an AccountAddress.
We could technically pass `AccountAddress.from(input, { maxMissingChars: 63 })` to each invocation of the function, but that might be more complicated, and this is generally an error that won't occur often, since there are rarely addresses that start with more than 4 zeros.
The main reason it's failing now is because we test those addresses specifically.
> chore(ECO-3137): Fix account address parsing inputs and unit tests for account addresses with ts-sdk 1.37.1 requirements

- src/typescript/frontend/package.json
- src/typescript/package.json
- src/typescript/pnpm-lock.yaml
- src/typescript/sdk/jest.config.js
- src/typescript/sdk/package.json
- src/typescript/sdk/src/utils/account-address.ts
- src/typescript/sdk/tests/unit/hex.test.ts
- src/typescript/sdk/tests/unit/serialize-entry-args-to-json.test.ts
Updates some `pnpm audit` dependencies.  SDK update should be fully compatible.
(replaces https://github.com/econia-labs/emojicoin-dot-fun/pull/749)
None except existing tests.
> chore(ECO-3133): Update Aptos SDK, and override axios / cross-spawn

- src/typescript/frontend/src/components/pages/test-utils/local-publisher.ts
- src/typescript/sdk/tests/utils/helpers.ts
- src/typescript/sdk/tests/utils/test-accounts.ts
Example warning (from another PR's CI outputs):
```shell
console.warn
[Aptos SDK] It is recommended that private keys are AIP-80 compliant (https://github.com/aptos-foundation/AIPs/blob/main/aips/aip-80.md). You can fix the private key by formatting it with `PrivateKey.formatPrivateKey(privateKey: string, type: 'ed25519' | 'secp256k1'): string`.
18 |     }
19 |     const index = prefix as FundedAccountIndex;
> 20 |     const privateKey = new Ed25519PrivateKey(privateKeyString);
|                        ^
21 |     const account = Account.fromPrivateKey({ privateKey });
22 |     return [index, account];
23 |   })
at Function.parseHexInput (../node_modules/.pnpm/@aptos-labs+ts-sdk@1.37.1_axios@1.8.4_got@11.8.6/node_modules/@aptos-labs/ts-sdk/src/core/authenticationKey.ts:56:86)
at new Ae …
```
> chore(ECO-3144): Format local test private key strings per Aptos SDK warning

- src/typescript/frontend/src/components/pages/emojicoin/components/chat/useChatEventsQuery.tsx
- src/typescript/frontend/src/components/pages/launch-emojicoin/hooks/use-is-market-registered.ts
- src/typescript/frontend/src/components/pages/launch-emojicoin/hooks/use-register-market.ts
- src/typescript/frontend/src/components/pages/wallet/useSwapEventsQuery.ts
- src/typescript/frontend/src/lib/hooks/queries/use-num-markets.ts
- src/typescript/frontend/src/lib/utils/emojiColors/use-emoji-colors.ts
They should be fetched as little as possible. They're fetched every time the window regains focus. The broker/websockets should handle most new incoming events.
I've added `staleTime: TEN_SECONDS` to both of them so that they're not fetched more often than once every 10 seconds. This will still allow users that can't connect over websockets to see new swap/chat events but not every single time the page/component regains focus.
Tested it myself manually by watching the network tab. Ensured each type of request isn't made more than once every 10 seconds.
> fix(ECO-3154): Add `staleTime: TEN_SECONDS` to `useSwapEventsQuery` and `useChatEventsQuery`; refactor `useIsMarketRegistered` `staleTime`

- src/cloud-formation/deploy-indexer-alpha.yaml
- src/cloud-formation/deploy-indexer-fallback.yaml
- src/cloud-formation/deploy-indexer-production.yaml
- src/docker/compose.yaml
> chore(ECO-3159): Bump processor submodule to 7.0.1 everywhere and hot upgrade `alpha`

- src/cloud-formation/deploy-indexer-alpha.yaml
- src/cloud-formation/deploy-indexer-fallback.yaml
- src/cloud-formation/deploy-indexer-production.yaml
- src/docker/compose.yaml
- src/typescript/sdk/src/indexer-v2/types/index.ts
- src/typescript/sdk/src/indexer-v2/types/json-types.ts
- src/typescript/sdk/src/indexer-v2/types/postgres-numeric-types.ts
- src/typescript/sdk/src/types/arena-types.ts
Need to add the new types to the SDK to expose the fields in the view.
See https://github.com/econia-labs/aptos-indexer-processors/pull/116
Fairly straighforward to test it manually. The field should show up and be converted properly to bigints in the `route.ts` endpoint for `/api/historical-position?user=0x....`
> chore(ECO-3163): Add new last transaction version types to leaderboard view in the SDK

- src/typescript/frontend/package.json
- src/typescript/sdk/package.json
- Frontend has arena additions.
- SDK's APIs changed so it's technically breaking changes, although it's still in alpha so just a minor bump is fine.
> chore(ECO-3148): Bump frontend version to 1.7.0 and SDK to 0.6.0

- src/typescript/frontend/src/components/pages/arena/tabs/ChatTab.tsx
- src/typescript/frontend/src/components/pages/emojicoin/components/chat/ChatBox.tsx
- src/typescript/frontend/src/components/pages/emojicoin/components/trade-history/trade-history.tsx
> fix(ECO-3170): Fix swaps incorrect sorting; update chat sorting

- src/typescript/frontend/src/app/wallet/utils.ts
A failure to resolve the name could mean one of two things:
- The ANS service is down.
- The user is on a local network (which also means it's down...)
In either case, it's still desirable to return the regular account address if it's valid, so this changes that so that it more gracefully handles the failure to fetch the ANS name, rather than says "User Not Found".
> fix(ECO-3171): Handle ANS name resolution failure gracefully

- .github/workflows/ts-checks.yaml
- src/cloud-formation/deploy-indexer-alpha.yaml
- src/cloud-formation/deploy-indexer-fallback.yaml
- src/cloud-formation/deploy-indexer-production.yaml
- src/docker/compose.yaml
- src/typescript/package.json
- src/typescript/sdk/package.json
- src/typescript/sdk/tests/e2e/arena/restart.test.ts
- src/typescript/sdk/tests/utils/docker/docker-test-harness.ts
- src/typescript/turbo.json
This PR adds E2E tests that include processor restarts to test the initialization of data in the processor.
> test(ECO-3175): Add E2E test with processor restarts

- src/typescript/frontend/src/app/arena/page.tsx
- src/typescript/frontend/src/app/home/fetch-melee-data.ts
- src/typescript/frontend/src/components/pages/arena/ArenaClient.tsx
- src/typescript/frontend/src/components/pages/arena/RewardsRemainingBox.tsx
- src/typescript/frontend/src/components/pages/arena/utils.tsx
- src/typescript/frontend/src/hooks/use-rewards-remaining.ts
- src/typescript/frontend/src/lib/store/arena/event/store.ts
- src/typescript/frontend/src/lib/store/event/event-store.ts
- src/typescript/sdk/src/indexer-v2/queries/app/arena.ts
- Take into account vault balance.
- Take into account distributed rewards since last querying of remaining
rewards
- Take into account collected tap out fees since last querying of
remaining rewards
- Take into account a new melee
> feat(ECO-3123): Implement rewards remaining tracking

- src/cloud-formation/deploy-indexer-alpha.yaml
- src/cloud-formation/deploy-indexer-fallback.yaml
- src/cloud-formation/deploy-indexer-production.yaml
- src/docker/compose.yaml
Tested the image locally to make sure it works. It did!
> chore(ECO-3191): Bump processor submodule for 7.0.4 (fixes rewards remaining calculations)

- src/typescript/frontend/src/components/charts/PrivateChart.tsx
- src/typescript/frontend/src/components/charts/const.ts
Tested locally, will also test on the preview.
> fix(ECO-3198): Fix default candlestick time for non-arena charts

- src/typescript/frontend/src/components/pages/arena/tabs/enter-tab/EnterTabLockPhase.tsx
- src/typescript/frontend/src/components/pages/arena/tabs/enter-tab/MatchAmount.tsx
- src/typescript/frontend/src/components/pages/arena/tabs/utils.tsx
https://github.com/user-attachments/assets/d5972382-df42-4be2-81b2-6f0159b6524f
> feat(ECO-3207): Update match amount UI

- src/typescript/frontend/src/components/charts/get-bars.ts
- src/typescript/frontend/src/components/charts/use-datafeed.ts
- src/typescript/frontend/src/lib/store/arena/event/utils.ts
- src/typescript/frontend/src/lib/store/event/candlestick-bars.ts
- src/typescript/frontend/src/lib/store/event/event-store.ts
- src/typescript/frontend/src/lib/store/event/types.ts
> fix(ECO-3209): Fix arena candlesticks

- src/typescript/frontend/src/lib/hooks/queries/use-wallet-balance.ts
This was introduced when I switched from using `Balance.view` to the Aptos TS SDK's `aptos.fungibleAsset.getCurrentFungibleAssetBalances` function.
It slipped my mind that the TS SDK doesn't automatically format addresses for us. It's a fairly simple fix- already tested it.
Already tested it with the address given on Discord (the user who reported the problem):
I hard-coded my address to `0x67212a9b61e40c0a543e3b25ba72c78ec74cd17916a68fd3e3bf22ea1b9aba7a` in the frontend and made sure the query works and the balance displays properly with the fix.
> fix(ECO-3239): Fix FA graphql query by removing leading zeros

- src/typescript/frontend/src/components/pages/emojicoin/components/main-info/MainInfo.tsx
- src/typescript/frontend/src/lib/store/user-settings-store.ts
Adds USD/APT toggle to user settings in local storage
Go to /market/droplet page, toggle the APT/USD$ switch on, and reload the page. The state should be saved.
> feat(ECO-3131): Add USD/APT toggle to user settings in local storage

- src/typescript/frontend/src/components/pages/arena/tabs/InfoTab.tsx
- src/typescript/frontend/src/lib/env.ts
Fixes the text and makes the link clickable
Visit /arena page, select info tab and scroll to bottom
> fix(ECO-3224): Update the link in the arena Info tab to be properly hyperlinked

- .github/workflows/pre-commit.yaml
- cfg/pre-commit-config.yaml
`pre-commit` seems to be failing consistently lately in CI due to an invalid venv.
See this failed run: https://github.com/econia-labs/emojicoin-dot-fun/actions/runs/14499155811/job/40676172151?pr=807
I believe the main issue was disparate python versions, which I fixed by pinning the default python version in pre-commit-config.yaml. This also consolidates the pre-commit caches (there were multiple caches with multiple python versions being used, one for each version used in different pre-commit hooks)
I also:
The path used wasn't valid `path: '${{ runner.home }}/.local/src/python/hooks'`.
I believe the poetry install is already cached by the `snok/install-poetry` action.
Proof: old logs output `Cache not found for input keys: poetry-1.8.2`, see here for example …
> fix(ECO-3246): Fix/update pre-commit GitHub Action caches

- src/typescript/frontend/package.json
- src/typescript/frontend/src/components/inputs/search-bar.tsx
- src/typescript/frontend/src/components/pages/arena/ArenaClient.tsx
- src/typescript/frontend/src/components/pages/arena/tabs/ArenaLoading.tsx
- src/typescript/frontend/src/components/pages/arena/tabs/InfoTab.tsx
- src/typescript/frontend/src/components/pages/arena/tabs/enter-tab/EnterTab.tsx
- src/typescript/frontend/src/components/pages/arena/tabs/enter-tab/EnterTabAmountPhase.tsx
- src/typescript/frontend/src/components/pages/arena/tabs/enter-tab/EnterTabLockPhase.tsx
- src/typescript/frontend/src/components/pages/arena/tabs/enter-tab/EnterTabPickPhase.tsx
- src/typescript/frontend/src/components/pages/arena/tabs/enter-tab/summary/EnterTabSummary.tsx
- src/typescript/frontend/src/components/pages/arena/tabs/enter-tab/summary/Summary.tsx
- src/typescript/frontend/src/components/pages/arena/tabs/enter-tab/summary/SwapModal.tsx
- src/typescript/frontend/src/components/pages/arena/tabs/enter-tab/summary/TapOutModal.tsx
- src/typescript/frontend/src/components/pages/arena/tabs/index.tsx
- src/typescript/frontend/src/components/pages/emojicoin/components/chat/ChatBox.tsx
- src/typescript/frontend/src/components/pages/emojicoin/components/desktop-grid/index.tsx
- src/typescript/frontend/src/components/pages/emojicoin/components/mobile-grid/index.tsx
- src/typescript/frontend/src/components/pages/wallet/WalletClientPage.tsx
- src/typescript/frontend/src/components/synced-scrollview.tsx
- src/typescript/frontend/src/components/ui/table/table.tsx
- src/typescript/frontend/src/components/ui/tabs/tabs.tsx
- src/typescript/frontend/tailwind.config.js
- Add new design for tabs: https://www.figma.com/design/gPCK4ByZV718N8GPd7MPm0/Econia-Labs-%7C-emojicoin.fun?node-id=15869-1526&p=f&t=OPdjA0H3FiLidbQN-0
- Update market page with new tabs
- Update portfolio page with new tabs
- Update arena page with new tabs
- Add a workaround to move the scollbar to the top of the tabs
- Some cleanup in the arena tabs content to make it consistent
- Visit pages /arena, 
- I took some liberties for some of the designs. For example the background of the tabs content on the Arena page is now a different tint to match with the tint of the selected header. Some of these designs are to be discussed
No checklist
> feat(ECO-2323): Add tabs UX/UI to the emojicoin page

- src/cloud-formation/deploy-indexer-alpha.yaml
- src/cloud-formation/deploy-indexer-fallback.yaml
- src/cloud-formation/deploy-indexer-production.yaml
- src/docker/compose.yaml
- src/typescript/frontend/package.json
- src/typescript/sdk/package.json
> chore(ECO-3242): Bump processor to 7.0.5 everywhere; bump frontend/SDK versions

- src/typescript/frontend/src/components/header/components/mobile-menu/index.tsx
- src/typescript/frontend/src/components/header/wallet-button/ConnectWalletButton.tsx
- src/typescript/frontend/src/components/pages/arena/tabs/enter-tab/EnterTab.tsx
- src/typescript/frontend/src/components/pages/arena/tabs/enter-tab/summary/EnterTabSummary.tsx
- src/typescript/frontend/src/components/pages/arena/tabs/index.tsx
- src/typescript/frontend/src/components/pages/emojicoin/components/chat/ChatBox.tsx
- src/typescript/frontend/src/components/pages/emojicoin/components/mobile-grid/index.tsx
- src/typescript/frontend/src/components/pages/emojicoin/components/mobile-grid/styled.tsx
- src/typescript/frontend/src/components/ui/tabs/tabs.tsx
- src/typescript/frontend/src/theme/base.ts
> fix(ECO-3249): Add fixes to arena UI improvements

- src/typescript/ci.env
- src/typescript/frontend/package.json
- src/typescript/frontend/src/lib/env.ts
- src/typescript/frontend/src/lib/utils/get-dynamic-base-fee-rate.ts
- src/typescript/frontend/tests/unit/calculate-swap-price.test.ts
- src/typescript/package.json
- src/typescript/sdk/package.json
- src/typescript/sdk/src/const.ts
- src/typescript/sdk/src/utils/validation/index.ts
- src/typescript/sdk/src/utils/validation/integer.ts
- src/typescript/sdk/tests/e2e/queries/client/submit.test.ts
> fix(ECO-3439): Add underflow handling to `getDynamicBaseFeeRateBPs`
